### ISSUE TITLE
Installing on OSMC

### ISSUE THREAD

**Issue by moskovskiy82** [mKeRix/room-assistant#10]
I know that it's not directly supported but when installing get the following error

root:/home/osmc/room-assistant# sudo npm install --unsafe-perm
room-assistant@0.2.0 /home/osmc/room-assistant
└─┬ temper1@0.0.7
  └─┬ node-hid@0.5.4
    └─┬ node-pre-gyp@0.6.31
      └─┬ nopt@3.0.6
        └── abbrev@1.0.9

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/noble/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN enoent ENOENT: no such file or directory, open '/home/osmc/room-assistant/node_modules/node-hid/node_modules/abbrev/package.json'

**Comment by moskovskiy82** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/noble/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm ERR! Linux 4.4.27-7-osmc
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path /home/osmc/room-assistant
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/home/osmc/room-assistant'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/home/osmc/room-assistant'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/osmc/room-assistant' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 4.4.27-7-osmc
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path npm-debug.log.557227212
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.557227212'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.557227212'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.557227212' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/osmc/room-assistant/npm-debug.log

**Comment by moskovskiy82** [comment]
Somehow i have solved that problem was with hid. Had to comile it manually. But now in the logs


Error: Cannot find module '../build/Release/binding.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/osmc/room-assistant/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error: Forever detected script exited with code: 1
error: Script restart attempt #8
module.js:471
    throw err;
    ^

**Comment by moskovskiy82** [comment]
As soon as i disable 
  "ble": {
    "enabled": false,
everything is starting up.

**Comment by moskovskiy82** [comment]
And this is with ble true

 cat /home/osmc/room-assistant/config/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle room-assistant@0.2.0~prestart: room-assistant@0.2.0
6 silly lifecycle room-assistant@0.2.0~prestart: no script for prestart, continuing
7 info lifecycle room-assistant@0.2.0~start: room-assistant@0.2.0
8 verbose lifecycle room-assistant@0.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle room-assistant@0.2.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/osmc/room-assistant/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/osmc/bin:/opt/vc/bin
10 verbose lifecycle room-assistant@0.2.0~start: CWD: /home/osmc/room-assistant
11 silly lifecycle room-assistant@0.2.0~start: Args: [ '-c', 'node index.js' ]
12 silly lifecycle room-assistant@0.2.0~start: Returned: code: 1  signal: null
13 info lifecycle room-assistant@0.2.0~start: Failed to exec start script
14 verbose stack Error: room-assistant@0.2.0 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid room-assistant@0.2.0
16 verbose cwd /home/osmc/room-assistant/config
17 error Linux 4.4.27-7-osmc
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error room-assistant@0.2.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the room-assistant@0.2.0 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the room-assistant package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs room-assistant
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls room-assistant
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by moskovskiy82** [comment]
After several hours of struggle. What helped me out

**Comment by mKeRix** [comment]
Well this is certainly interesting, thanks for documenting your progress for everyone else! If it does not report back with any errors the Bluetooth component should indeed be loaded fine, however something seems to be off considering it's not showing you what the hcitool is seeing. Have you made sure that the whitelist is empty/disabled? And maybe just to make sure try running it as root once?

If that doesn't deliver any results we'll have to dig a little deeper. There's no such in depth debug mode in place yet, but I could write a script that just outputs everything that the BLE library "noble" sees. There's some troubleshooting information on the bottom of their documentation page too, maybe some of that could help: https://www.npmjs.com/package/noble

**Comment by moskovskiy82** [comment]
Well i tried to run it as root. As to instruction i have set it to the service. 
root       563  0.1  4.1 119108 30984 ?        Sl   feb05   1:12 /usr/bin/nodejs /home/osmc/room-assistant/index.js

Everything is loading up correctly per log
error: Forever detected script was killed by signal: SIGTERM
                                            Starting Room Assistant...
                                            Connected to MQTT server
                                            BLE scanner was initialized

Will try to troubleshoot with noble

**Comment by moskovskiy82** [comment]
Still out of any luck.

**Comment by mKeRix** [comment]
I currently can't think of anything else to suggest you sadly - I'll try to fire up a VM with OSMC if I find some time on the weekend.

**Comment by moskovskiy82** [comment]
What i have also noticed it the following. Maybe it's worth uninstalling these and get them from some other rep? Any recommendations?

ii  armv7-bluez-osmc                          5.3.9-1                   armhf                     bluez for OSMC
ii  bluetooth                                 5.23-2                    all                       Bluetooth support
ii  bluez                                     9.99-9                    all                       bluez transitional package for OSMC
ii  libbluetooth-dev                          5.23-2+b1                 armhf                     Development files for using the BlueZ Linux Bluetooth library
ii  libbluetooth3:armhf                       5.23-2+b1                 armhf                     Library to use the BlueZ Linux Bluetooth stack

**Comment by mKeRix** [comment]
Closing because I couldn't reproduce this myself and there has been no activity for a while now. Please reopen if the issue persists.
