### ISSUE TITLE
Room assistant won't start from hass.io add-on 

### ISSUE THREAD

**Issue by timwood** [mKeRix/room-assistant#100]
Hi! Looking forward to getting this add-on working with hass.io. But as it stands the add-on fails to start. I tried to capture part of the log output from the webUI (not even sure how to access this at the command line). I believe I've included the relevant parts. It seems there are no  prebuilt binaries found the below packages/dependencies for my environment. I'm running hass.io in Docker on an Intel-based computer running Ubuntu 18.04.

### Relevant logs
```
prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.2/usb-v1.6.2-node-v57-linuxmusl-ia32.tar.gz
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.2/usb-v1.6.2-node-v57-linuxmusl-ia32.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.14.0 runtime=node arch=ia32 libc=musl platform=linux)

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-4/binding-0.5.3-4-node-v57-linux-ia32.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @abandonware/bluetooth-hci-socket@0.5.3-4 and node@8.14.0 (node-v57 ABI, musl) (falling back to source compile with node-gyp) 
```

### Logs I was able to capture
```
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:643:187: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<v8::String>("endianness").ToLocalChecked(), Nan::New<v8::String>(CheckEndianness()).ToLocalChecked(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                                                                                                                           ^
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:644:8: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<v8::String>("NULL").ToLocalChecked(), WrapNullPointer(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
        ^~~~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:644:142: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<v8::String>("NULL").ToLocalChecked(), WrapNullPointer(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                                                                              ^
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/room-assistant/node_modules/ref/build'

> usb@1.6.2 install /room-assistant/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.3
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/e66075-usb-v1.6.2-node-v57-linuxmusl-ia32.tar.gz
prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.2/usb-v1.6.2-node-v57-linuxmusl-ia32.tar.gz
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.2/usb-v1.6.2-node-v57-linuxmusl-ia32.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.14.0 runtime=node arch=ia32 libc=musl platform=linux)
make: Entering directory '/room-assistant/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
In file included from ../libusb/libusb/os/linux_usbfs.c:43:0:
../libusb/libusb/os/linux_usbfs.h:24:25: fatal error: linux/types.h: No such file or directory
 #include <linux/types.h>
                         ^
compilation terminated.
make: *** [libusb.target.mk:138: Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o] Error 1
make: Leaving directory '/room-assistant/node_modules/usb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-74-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /room-assistant/node_modules/usb
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> @abandonware/bluetooth-hci-socket@0.5.3-4 install /room-assistant/node_modules/@abandonware/bluetooth-hci-socket
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-4/binding-0.5.3-4-node-v57-linux-ia32.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @abandonware/bluetooth-hci-socket@0.5.3-4 and node@8.14.0 (node-v57 ABI, musl) (falling back to source compile with node-gyp) 
make: Entering directory '/room-assistant/node_modules/@abandonware/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
  COPY /room-assistant/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/room-assistant/node_modules/@abandonware/bluetooth-hci-socket/build'

> epoll@2.0.10 install /room-assistant/node_modules/epoll
> node-gyp rebuild

make: Entering directory '/room-assistant/node_modules/epoll/build'
  CXX(target) Release/obj.target/epoll/src/epoll.o
  SOLINK_MODULE(target) Release/obj.target/epoll.node
  COPY Release/epoll.node
make: Leaving directory '/room-assistant/node_modules/epoll/build'

> ffi@2.2.0 install /room-assistant/node_modules/ffi
> node-gyp rebuild

make: Entering directory '/room-assistant/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o


 from ../src/ffi.cc:1:
/root/.node-gyp/8.14.0/include/node/v8.h:3165:22: note: declared here
                 bool ForceSet(Local<Value> key, Local<Value> value,
                      ^
/root/.node-gyp/8.14.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/ffi.cc: In static member function 'static void FFI::FinishAsyncFFICall(uv_work_t*)':
../src/ffi.cc:367:28: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   p->callback->Call(1, argv);
                            ^
In file included from ../src/ffi.h:23:0,
                 from ../src/ffi.cc:3:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
../src/callback_info.cc: In static member function 'static void CallbackInfo::DispatchToV8(callback_info*, void*, void**, bool)':
../src/callback_info.cc:63:55: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
         info->errorFunction->Call(1, errorFunctionArgv);
                                                       ^
In file included from ../src/ffi.h:23:0,
                 from ../src/callback_info.cc:8:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/callback_info.cc:73:58: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     Local<Value> e = info->function->Call(2, functionArgv);
                                                          ^
In file included from ../src/ffi.h:23:0,
                 from ../src/callback_info.cc:8:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/callback_info.cc:78:55: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
         info->errorFunction->Call(1, errorFunctionArgv);
                                                       ^
In file included from ../src/ffi.h:23:0,
                 from ../src/callback_info.cc:8:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/obj.target/ffi_bindings.node
  COPY Release/ffi_bindings.node
make: Leaving directory '/room-assistant/node_modules/ffi/build'

> d6t@0.0.5 postinstall /room-assistant/node_modules/d6t
> make -C library/src/ && sudo make -C library/src install

make: Entering directory '/room-assistant/node_modules/d6t/library/src'
gcc -c d6t.c -I../include -W -Wall -O2 -fpic
gcc -c i2c-reg.c -I../include -W -Wall -O2 -fpic
i2c-reg.c:44:27: fatal error: linux/i2c-dev.h: No such file or directory
 #include <linux/i2c-dev.h>
                           ^
compilation terminated.
make: *** [Makefile:23: i2c-reg.o] Error 1
make: Leaving directory '/room-assistant/node_modules/d6t/library/src'
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.2 (node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.2 install: `prebuild-install --verbose || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

{ Error: d6t@0.0.5 postinstall: `make -C library/src/ && sudo make -C library/src install`
Exit status 2
    at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  cause: 
   { Error: d6t@0.0.5 postinstall: `make -C library/src/ && sudo make -C library/src install`
Exit status 2
    at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
     errno: 2,
     code: 'ELIFECYCLE',
     pkgid: 'd6t@0.0.5',
     stage: 'postinstall',
     script: 'make -C library/src/ && sudo make -C library/src install',
     pkgname: 'd6t' },
  errno: 2,
  code: 'ELIFECYCLE',
  pkgid: 'd6t@0.0.5',
  stage: 'postinstall',
  script: 'make -C library/src/ && sudo make -C library/src install',
  pkgname: 'd6t',
  parent: 'room-assistant' }
```

Could you also help me understand whether I need to change any of the default room assistant configuration if I'm using hass.io and the Mosquitto broker add-on and intend to use a home assistant user.  Here is the default config, which I haven't changed.
```json
{
  "services": [],
  "room": "default-room",
  "mqtt": {
    "url": "mqtt://localhost",
    "username": "",
    "password": "",
    "rejectUnauthorized": true
  },
  "ble": {
    "channel": "room_presence",
    "useAddress": false,
    "whitelist": [],
    "maxDistance": 0,
    "updateFrequency": 0,
    "processIBeacon": true,
    "onlyIBeacon": false,
    "majorMask": "0xFFFF",
    "minorMask": "0xFFFF"
  },
  "gpio": [],
  "shell": []
}
```

**Comment by mKeRix** [comment]
Hey! From the looks of it the add-on tries to install the dependencies for the d6t component, which isn't supported on Hass.io yet. Could you try adding only the services you need to `services` (e.g. `services: ["mqtt", "ble"]`, see [here](https://github.com/mKeRix/room-assistant/wiki/Configuration)) and then start the add-on again?

**Comment by timwood** [comment]
Hi. Thanks for the amazingly fast response! I tried adding only the needed services (mqtt and ble) but got the same errors. Then I tried just mqtt and it started successfully!

```
> room-assistant@1.1.1 start /room-assistant
> bin/room-assistant-runner.js

Installing dependencies for: mqtt
Packages needed: mqtt@2.18.8
Already installed: 
Now installing: mqtt@2.18.8
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.

+ mqtt@2.18.8
added 61 packages from 46 contributors and audited 52 packages in 7.025s
found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[2020-01-25T21:01:43.845Z] INFO  6e66619d-room-assistant.local.hass.io-36/BROKER: Moleculer v0.13.4 is starting...
[2020-01-25T21:01:43.853Z] INFO  6e66619d-room-assistant.local.hass.io-36/BROKER: Node ID: 6e66619d-room-assistant.local.hass.io-36
[2020-01-25T21:01:43.854Z] INFO  6e66619d-room-assistant.local.hass.io-36/BROKER: Namespace: <not defined>
[2020-01-25T21:01:43.856Z] INFO  6e66619d-room-assistant.local.hass.io-36/REGISTRY: Strategy: RoundRobinStrategy
[2020-01-25T21:01:43.864Z] INFO  6e66619d-room-assistant.local.hass.io-36/BROKER: Serializer: JSONSerializer
[2020-01-25T21:01:43.868Z] INFO  6e66619d-room-assistant.local.hass.io-36/BROKER: Registered 10 internal middleware(s).
[2020-01-25T21:01:44.238Z] INFO  6e66619d-room-assistant.local.hass.io-36/REGISTRY: '$node' service is registered.
[2020-01-25T21:01:44.243Z] INFO  6e66619d-room-assistant.local.hass.io-36/REGISTRY: 'mqtt' service is registered.
[2020-01-25T21:01:44.245Z] INFO  6e66619d-room-assistant.local.hass.io-36/BROKER: ServiceBroker with 2 service(s) is started successfully.
[2020-01-25T21:01:44.275Z] INFO  6e66619d-room-assistant.local.hass.io-36/MQTT: Connected to mqtt://localhost
```

How do I know whether it's successfully connected (and authenticated?) to the hass.io Mosquitto broker add-on? 

Can I use this with google home devices as the per-room bluetooth beacons?

**Comment by mKeRix** [comment]
The line `Connected to mqtt://localhost` from the logs you posted suggests it connected successfully. :) Could you post a log of the errors that you get when you enable the services you need (excluding d6t)?

room-assistant is something you put on a bunch of devices (e.g. Pi Zeros) spread across your home, it then tracks mobile Bluetooth beacons. I guess technically you could also track Google Home devices themselves - but these will likely not move across your home, so that likely doesn't achieve the same effect. It is not meant to connect to Google Homes and then track tags from there. If that is what you want to achieve I think there was a Google Home device tracker component directly for Home Assistant somewhere?

**Comment by mrand** [comment]
>  I think there was a Google Home device tracker component directly for Home Assistant somewhere?

After Google added tokens last year, using a google home as a tracker now requires a rooted android device (or you might be able to run android within a VM) and this custom component: https://github.com/Drakulix/googlehome

**Comment by mKeRix** [comment]
This shouldn’t be an issue anymore starting with 2.0!
