### ISSUE TITLE
Can't Start With Services

### ISSUE THREAD

**Issue by soloam** [mKeRix/room-assistant#101]
Hello, I can run the service with the npm start on the forlder of the room-assistant, but I installed the service like stated in the github page and when I try to start the service, I get this error on the log:

```
jan 26 02:26:32 raspberrypi systemd[1]: Started Room Assistant service.
jan 26 02:26:43 raspberrypi npm[2703]: (node:2703) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
jan 26 02:26:44 raspberrypi npm[2703]: > room-assistant@1.1.2-dev start /home/pi/room-assistant
jan 26 02:26:44 raspberrypi npm[2703]: > bin/room-assistant-runner.js
jan 26 02:26:55 raspberrypi npm[2703]: (node:2730) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
jan 26 02:26:55 raspberrypi npm[2703]: Installing dependencies for: mqtt,ble,shell,console
jan 26 02:26:55 raspberrypi npm[2703]: Packages needed: mqtt@2.18.8,@abandonware/noble@1.9.2-3
jan 26 02:27:05 raspberrypi npm[2703]: Already installed: mqtt@2.18.8
jan 26 02:27:05 raspberrypi npm[2703]: Now installing: @abandonware/noble@1.9.2-3
jan 26 02:27:08 raspberrypi npm[2703]: { Error: Method Not Allowed
jan 26 02:27:08 raspberrypi npm[2703]:     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
jan 26 02:27:08 raspberrypi npm[2703]:     at /usr/share/npm/lib/cache/add-named.js:120:12
jan 26 02:27:08 raspberrypi npm[2703]:     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
jan 26 02:27:08 raspberrypi npm[2703]:     at FSReqWrap.oncomplete (fs.js:135:15)
jan 26 02:27:08 raspberrypi npm[2703]:   statusCode: 405,
jan 26 02:27:08 raspberrypi npm[2703]:   code: 'E405',
jan 26 02:27:08 raspberrypi npm[2703]:   pkgid: 'abandonware/noble',
jan 26 02:27:08 raspberrypi npm[2703]:   parent: 'room-assistant' }
jan 26 02:27:18 raspberrypi systemd[1]: room-assistant.service: Service hold-off time over, scheduling restart.
jan 26 02:27:18 raspberrypi systemd[1]: Stopped Room Assistant service.
jan 26 02:27:18 raspberrypi systemd[1]: Started Room Assistant service.
jan 26 02:27:28 raspberrypi npm[2798]: (node:2798) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
jan 26 02:27:29 raspberrypi npm[2798]: > room-assistant@1.1.2-dev start /home/pi/room-assistant
jan 26 02:27:29 raspberrypi npm[2798]: > bin/room-assistant-runner.js
jan 26 02:27:39 raspberrypi npm[2798]: (node:2809) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
jan 26 02:27:40 raspberrypi npm[2798]: Installing dependencies for: mqtt,ble,shell,console
jan 26 02:27:40 raspberrypi npm[2798]: Packages needed: mqtt@2.18.8,@abandonware/noble@1.9.2-3
jan 26 02:27:49 raspberrypi npm[2798]: Already installed: mqtt@2.18.8
jan 26 02:27:49 raspberrypi npm[2798]: Now installing: @abandonware/noble@1.9.2-3
jan 26 02:27:52 raspberrypi npm[2798]: { Error: Method Not Allowed
jan 26 02:27:52 raspberrypi npm[2798]:     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
jan 26 02:27:52 raspberrypi npm[2798]:     at /usr/share/npm/lib/cache/add-named.js:120:12
```

**Comment by soloam** [comment]
This is strange, because if I start with "npm start" I see:

```
pi@raspberrypi:~/apps/room-assistant $ npm start

> room-assistant@1.1.2-dev start /home/pi/apps/room-assistant
> bin/room-assistant-runner.js

Installing dependencies for: mqtt,ble
Packages needed: mqtt@2.18.8,@abandonware/noble@1.9.2-3
Already installed: @abandonware/noble@1.9.2-3,mqtt@2.18.8
Now installing:
[2020-01-26T04:01:07.776Z] INFO  raspberrypi-3774/BROKER: Moleculer v0.13.9 is starting...
[2020-01-26T04:01:07.833Z] INFO  raspberrypi-3774/BROKER: Node ID: raspberrypi-3774
[2020-01-26T04:01:07.840Z] INFO  raspberrypi-3774/BROKER: Namespace: <not defined>
[2020-01-26T04:01:07.853Z] INFO  raspberrypi-3774/REGISTRY: Strategy: RoundRobinStrategy
[2020-01-26T04:01:07.889Z] INFO  raspberrypi-3774/BROKER: Serializer: JSONSerializer
[2020-01-26T04:01:07.913Z] INFO  raspberrypi-3774/BROKER: Registered 10 internal middleware(s).
[2020-01-26T04:01:11.787Z] INFO  raspberrypi-3774/REGISTRY: '$node' service is registered.
[2020-01-26T04:01:11.815Z] INFO  raspberrypi-3774/REGISTRY: 'mqtt' service is registered.
[2020-01-26T04:01:11.825Z] INFO  raspberrypi-3774/REGISTRY: 'ble' service is registered.
[2020-01-26T04:01:11.833Z] INFO  raspberrypi-3774/BROKER: ServiceBroker with 3 service(s) is started successfully.
```

But if I go with service start:

```
jan 26 04:02:54 raspberrypi systemd[1]: Started Room Assistant service.
jan 26 04:03:06 raspberrypi npm[3831]: (node:3831) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
jan 26 04:03:08 raspberrypi npm[3831]: > room-assistant@1.1.2-dev start /home/pi/apps/room-assistant
jan 26 04:03:08 raspberrypi npm[3831]: > bin/room-assistant-runner.js
jan 26 04:03:19 raspberrypi npm[3831]: (node:3846) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
jan 26 04:03:19 raspberrypi npm[3831]: Installing dependencies for: mqtt,ble
jan 26 04:03:19 raspberrypi npm[3831]: Packages needed: mqtt@2.18.8,@abandonware/noble@1.9.2-3
jan 26 04:03:30 raspberrypi npm[3831]: Already installed: mqtt@2.18.8
jan 26 04:03:30 raspberrypi npm[3831]: Now installing: @abandonware/noble@1.9.2-3
jan 26 04:03:33 raspberrypi npm[3831]: { Error: Method Not Allowed
jan 26 04:03:33 raspberrypi npm[3831]:     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
jan 26 04:03:33 raspberrypi npm[3831]:     at /usr/share/npm/lib/cache/add-named.js:120:12
jan 26 04:03:33 raspberrypi npm[3831]:     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
jan 26 04:03:33 raspberrypi npm[3831]:     at FSReqWrap.oncomplete (fs.js:135:15)
jan 26 04:03:33 raspberrypi npm[3831]:   statusCode: 405,
jan 26 04:03:33 raspberrypi npm[3831]:   code: 'E405',
jan 26 04:03:33 raspberrypi npm[3831]:   pkgid: 'abandonware/noble',
jan 26 04:03:33 raspberrypi npm[3831]:   parent: 'room-assistant' }
```
It looks like in service it tries to install "@abandonware/noble@1.9.2-3" that in "npm start" is already installed.

Thank You

**Comment by mKeRix** [comment]
This is an npm error - most likely either HTTP or filesystem permissions related. Are you running the service with a different user than if you start it directly? Do you have some kind of proxy configured? Are you using an up-to-date version of Node (12.x) and npm (6.x)?

**Comment by soloam** [comment]
This is a Pi zero that I run with the Pi user! Node version 10.15. 3, the install was done with pi user, and the room assistant runs without a problem with npm start! It fails to start with the service. It's strange

**Comment by mKeRix** [comment]
Does the same issue occur if you run the service from a clean `node_modules`? So `rm -R node_modules` followed by `npm install --production` in the room-assistant directory, but then start room-assistant as the service (not manually!).

**Comment by soloam** [comment]
Yes! I did that, the same, world with npm start, but not service! It looks from the log that is attempting to install a package, but fails!

**Comment by mKeRix** [comment]
Indeed - unfortunately this is not a room-assistant specific error and also quite generic, so it's very hard to tell what's the actual issue. When installing packages room-assistant just uses the systemwide npm. Googling "npm method not allowed" results in a whole bunch of different suggestions, talking about proxies, npm configs... I checked the official npm site and the package is still published with the same version number. I'm really at a loss here.

**Comment by soloam** [comment]
I think I'll install raspbian from scratch and try again!

Thank you @mKeRix, we can close this issue!
