### ISSUE TITLE
Home/Room Assistant cannot find my Samsung S20+ device

### ISSUE THREAD

**Issue by bachoo786** [mKeRix/room-assistant#1129]
**Describe the bug**
I have the Home Assistant App on my Samsung Galaxy S20+ installed and I have enabled the BLE Transmitter Sensor with high power etc I have also obtained the UUID and the ID within the BLE Sensor section of the Home Assistant App. I have then entered my ID on my room assistant configuration but for the life of me, my phone does not get detected at all. 

I am running 4 instances of RA and I also deleted the HA Android App from my S20+ and reinstalled it again hoping it would work but no joy. Almost ready to give up !

PS. I have checked that the issue is NOT from the HA Android App as I can see the BLE sensor in my HA showing that its transmitting fine.

![image](https://user-images.githubusercontent.com/6251030/160872528-f78f87f3-d017-4585-8e07-fc24929974d1.png)

**To reproduce**
Run RA and watch the S20+ is not detected at all.

**Relevant logs**

```*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
30/03/2022, 16:21:01 - info - IntegrationsModule: Loading integrations: none
30/03/2022, 16:21:05 - info - NestFactory: Starting Nest application...
30/03/2022, 16:21:06 - info - InstanceLoader: AppModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: ConfigModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: NestEmitterModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: IntegrationsModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: DiscoveryModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: PrometheusModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: EventsModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: TerminusModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: ClusterModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: ScheduleModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: EntitiesModule dependencies initialized
30/03/2022, 16:21:06 - info - InstanceLoader: StatusModule dependencies initialized
30/03/2022, 16:21:14 - info - WebSocketsController: EventsGateway subscribed to the "subscribeEvents" message
30/03/2022, 16:21:14 - info - RoutesResolver: EntitiesController {/entities}:
30/03/2022, 16:21:14 - info - RouterExplorer: Mapped {/entities, GET} route
30/03/2022, 16:21:14 - info - RoutesResolver: StatusController {/status}:
30/03/2022, 16:21:14 - info - RouterExplorer: Mapped {/status, GET} route
30/03/2022, 16:21:14 - info - RoutesResolver: PrometheusController {/metrics}:
30/03/2022, 16:21:14 - info - RouterExplorer: Mapped {/metrics, GET} route
30/03/2022, 16:21:14 - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js, /opt/nodejs/lib/node_modules/room-assistant/dist       /config/definitions/custom-environment-variables.yml (Current: /home/pi/room-assistant/config)
30/03/2022, 16:21:15 - info - ClusterService: Starting mDNS advertisements and discovery
30/03/2022, 16:21:15 - debug - EntitiesService: Adding new entity status-cluster-size
30/03/2022, 16:21:15 - debug - EntitiesService: Adding new entity status-cluster-leader
30/03/2022, 16:21:15 - debug - HealthIndicatorService: Systemd watchdog reporting is unavailable, as the optional sd-notify dependency could not be loaded
30/03/2022, 16:21:15 - info - NestApplication: Nest application successfully started
30/03/2022, 16:21:15 - error - undefined: Error: listen EADDRINUSE: address already in use :::6415
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: listen EADDRINUSE: address already in use :::6415
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1465:7)
    at ExpressAdapter.listen (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@nestjs/platform-express/adapters/express-adapter.js:63:32)
    at /opt/nodejs/lib/node_modules/room-assistant/node_modules/@nestjs/core/nest-application.js:167:30
    at new Promise (<anonymous>)
    at NestApplication.listen (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@nestjs/core/nest-application.js:156:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bootstrap (/opt/nodejs/lib/node_modules/room-assistant/dist/main.js:32:5) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 6415
}

```

**Relevant configuration**

```global:
  instanceName: Master Bedroom
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://XXX:1883'
  mqttOptions:
    username: XXXX
    password: XXXX
bluetoothLowEnergy:
  timeout: 60
  allowlist:
    - e01fcf8c-1d6d-48ce-8776-a7ec5ec9a2f9-100-1
    - 410588B6-BCF9-47FD-ACE5-90E776F3A6C5
  maxDistance: 5
  minDiscoveryLogRssi: -30
  tagOverrides:
    e01fcf8c-1d6d-48ce-8776-a7ec5ec9a2f9-100-1:
      name: S20+ BLE
    410588B6-BCF9-47FD-ACE5-90E776F3A6C5:
      name: Iphone BLE

cluster:
  autoDiscovery: false
  port: 6425
  peerAddresses:
    - 192.XXX.XX.XXX:6425
    - 192.XXX.XX.XXX:6425
    - 192.XXX.XX.XXX:6425
  weight: 8
  quorum: 2

```

**Expected behavior**
I expect my S20+ to be connected to the MQTT and shown in my HA. I have connected my Iphone via the room-assistant ios app and its working perfectly. However my S20+ using the HA app as the BLE Transmitter does not work. 

**Environment**
 - room-assistant version: 2.20.0
 - installation type: NodeJS
 - hardware: 2x Raspberry Pi Zero W, 1x Raspberry Pi 3b+, 1x Docker
 - OS: Linux

**Comment by jcruz1013** [comment]
I get the same
