### ISSUE TITLE
rpi4 with bullseye doesn't get mdns to work with room-assistant

### ISSUE THREAD

**Issue by Draganis** [mKeRix/room-assistant#1237]
**Describe the bug**
I get an error with room-assistant on startup regarding mdns. This is not too bad, because i can use room-assistant without mdns working. But i cannot use it as a service, because the error triggers the service to stop (because of an error)
`pi@MirrorPi1:~ $ npm list
pi@ /home/pi
└── mdns@2.7.2

pi@MirrorPi1:~ $ room-assistant &
[1] 4362
pi@MirrorPi1:~ $ [Nest] 4362  - 13/08/2022, 17:10:41   ERROR [ClusterService] Cannot find module 'mdns'
Require stack:
- /usr/local/lib/node_modules/room-assistant/dist/cluster/cluster.service.js
- /usr/local/lib/node_modules/room-assistant/dist/entities/entities.service.js
- /usr/local/lib/node_modules/room-assistant/dist/entities/entities.module.js
- /usr/local/lib/node_modules/room-assistant/dist/app.module.js
- /usr/local/lib/node_modules/room-assistant/dist/main.js
- /usr/local/lib/node_modules/room-assistant/bin/room-assistant.js
Error: Cannot find module 'mdns'`

**To reproduce**
I installed piOS bullseye on a rpi3/rpi4 (both have the same errors)
then i worked myself through the setup instructions on https://www.room-assistant.io/guide/installation.html#installation-1
Even without any config file the error is getting up.
If i run room-assistant in docker, the error doesn't show up.
If i setup my /home/pi/room-assistant/config/local.yml file like below it still happens:

**Relevant logs**
`room-assistant -v` shows as follows
`pi@MirrorPi1:~ $ room-assistant -v
[Nest] 6351  - 13/08/2022, 17:20:13   ERROR [ClusterService] Cannot find module 'mdns'
Require stack:
- /usr/local/lib/node_modules/room-assistant/dist/cluster/cluster.service.js
- /usr/local/lib/node_modules/room-assistant/dist/entities/entities.service.js
- /usr/local/lib/node_modules/room-assistant/dist/entities/entities.module.js
- /usr/local/lib/node_modules/room-assistant/dist/app.module.js
- /usr/local/lib/node_modules/room-assistant/dist/main.js
- /usr/local/lib/node_modules/room-assistant/bin/room-assistant.js
Error: Cannot find module 'mdns'
Require stack:
- /usr/local/lib/node_modules/room-assistant/dist/cluster/cluster.service.js
- /usr/local/lib/node_modules/room-assistant/dist/entities/entities.service.js
- /usr/local/lib/node_modules/room-assistant/dist/entities/entities.module.js
- /usr/local/lib/node_modules/room-assistant/dist/app.module.js
- /usr/local/lib/node_modules/room-assistant/dist/main.js
- /usr/local/lib/node_modules/room-assistant/bin/room-assistant.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/room-assistant/dist/cluster/cluster.service.js:49:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
13/08/2022, 17:20:16 - info - IntegrationsModule: Loading integrations: none
13/08/2022, 17:20:17 - info - NestFactory: Starting Nest application...
13/08/2022, 17:20:17 - info - InstanceLoader: AppModule dependencies initialized
13/08/2022, 17:20:17 - info - InstanceLoader: ConfigModule dependencies initialized
13/08/2022, 17:20:17 - info - InstanceLoader: NestEmitterModule dependencies initialized
13/08/2022, 17:20:17 - info - InstanceLoader: IntegrationsModule dependencies initialized
13/08/2022, 17:20:18 - info - InstanceLoader: DiscoveryModule dependencies initialized
13/08/2022, 17:20:18 - info - InstanceLoader: PrometheusModule dependencies initialized
13/08/2022, 17:20:18 - info - InstanceLoader: EventsModule dependencies initialized
13/08/2022, 17:20:18 - info - InstanceLoader: TerminusModule dependencies initialized
13/08/2022, 17:20:18 - info - InstanceLoader: ClusterModule dependencies initialized
13/08/2022, 17:20:18 - info - InstanceLoader: ScheduleModule dependencies initialized
13/08/2022, 17:20:18 - info - InstanceLoader: EntitiesModule dependencies initialized
13/08/2022, 17:20:18 - info - InstanceLoader: StatusModule dependencies initialized
13/08/2022, 17:20:19 - info - WebSocketsController: EventsGateway subscribed to the "subscribeEvents" message
13/08/2022, 17:20:19 - info - RoutesResolver: EntitiesController {/entities}:
13/08/2022, 17:20:19 - info - RouterExplorer: Mapped {/entities, GET} route
13/08/2022, 17:20:19 - info - RoutesResolver: StatusController {/status}:
13/08/2022, 17:20:19 - info - RouterExplorer: Mapped {/status, GET} route
13/08/2022, 17:20:19 - info - RoutesResolver: PrometheusController {/metrics}:
13/08/2022, 17:20:19 - info - RouterExplorer: Mapped {/metrics, GET} route
13/08/2022, 17:20:19 - info - ConfigService: Loading configuration from /usr/local/lib/node_modules/room-assistant/dist/config/definitions/default.js, /usr/local/lib/node_modules/room-assistant/dist/config/definitions/custom-environment-variables.yml (Current: /home/pi)
13/08/2022, 17:20:19 - warn - ClusterService: Dependency "mdns" was not found, automatic discovery has been disabled. You will have to provide the addresses of other room-assistant nodes manually in the config.
13/08/2022, 17:20:19 - debug - EntitiesService: Adding new entity status-cluster-size
13/08/2022, 17:20:19 - debug - EntitiesService: Adding new entity status-cluster-leader
13/08/2022, 17:20:19 - debug - HealthIndicatorService: Systemd watchdog reporting is unavailable, as the optional sd-notify dependency could not be loaded
13/08/2022, 17:20:19 - info - NestApplication: Nest application successfully started
13/08/2022, 17:20:20 - info - ClusterService: room1 has been elected as leader
13/08/2022, 17:20:20 - info - ClusterService: Added 172.16.XXX.51:6425 to the cluster with id room2
13/08/2022, 17:20:20 - info - ClusterService: Added 172.16.XXX.11:6425 to the cluster with id room3
13/08/2022, 17:20:21 - info - ClusterService: Added 172.16.XXX.217:6425 to the cluster with id room4`
```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```global:
  instanceName: room1
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
    - bluetoothClassic
cluster:
  peerAddresses:
    - 172.16.XXX.11
    - 172.16.XXX.2
    - 172.16.XXX.72
    - 172.16.XXX.217
    - 172.16.XXX.142
    - 172.16.XXX.51
    - 172.16.XXX.38
    - 172.16.XXX.97
homeAssistant:
  mqttUrl: "mqtt://172.16.XXX.XXX:1883"
  mqttOptions":
    username:"user"
    password:"password!"
bluetoothClassic:
  addresses:
    - FC:XX:XX:XX:XX:87
    - 00:DB:70:F1:D3:7F
bluetoothLowEnergy:
  timeout: 60
  allowlist:
    - ffffXXXXXX0
    - d11cXXXXXXX9
    - ffffXXXXXXXc
    - ffffXXXXXXX5
    - ffffXXXXXXX9
    - 90f1XXXXXXX1
```

**Expected behavior**
A clear and concise description of what you expected to happen:
I want to run room-assistant as a service without startup errors xD

**Environment**
 - room-assistant version: 2.20.0
 - installation type: NodeJS version (12.22.12~dfsg-1~deb11u1)
 - hardware: rpi3/rpi4
 - OS: piOS bullseye

**What i already tried**
Uninstall avahi and reinstall it
npm install mdns (and as mentioned above, npm has it in the installed list)

**Comment by Draganis** [comment]
Bumping this up. This is still not solved
