### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by hwikene** [mKeRix/room-assistant#132]
**Describe the bug**
Getting this error when running Room-assistant on Pi3 

**To reproduce**
Get this after i installed Room-assistant on my Home assistant

**Relevant logs**
```events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::6415
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at ExpressAdapter.listen (/usr/lib/node_modules/room-assistant/node_modules/@nestjs/platform-express/adapters/express-adapter.js:44:32)
    at NestApplication.listen (/usr/lib/node_modules/room-assistant/node_modules/@nestjs/core/nest-application.js:140:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1336:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 6415
}```

**Relevant configuration**
Paste the relevant parts of your configuration below.

Home assistant config: 
```global:
  instanceName: stue
  integrations:
    - homeAssistant
    - bluetoothClassic
  mqttUrl: 'mqtt://192.168.8.33:1883'
  mqttOptions:
    username: user
    password: pass
bluetoothClassic:
  minRssi: -20
  addresses:
    - '40:9C:28:03:01:CC'

Pi3 config: 
global:
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.8.33:1883'
  mqttOptions:
    username: user
    password: pass
bluetoothClassic:
  minRssi: -20
  addresses:
    - 40:9C:28:03:01:CC``` 


**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment**
 - room-assistant version: [e.g. 2.1.1]
 - installation type: [e.g. NodeJS, Docker, Hass.io]
 - hardware: [e.g. Raspberry Pi 3, NUC]
 - OS: Ubuntu server 18.04]

**Additional context**
Add any other context about the problem here.

**Comment by mKeRix** [comment]
Most likely happened when you have two instances of room-assistant running at the same time, maybe one as a service if you followed the quickstart guide. The application is trying to pick up the port 6415, but it's already being used by another process. Stop your service/other instance of room-assistant before starting a new one.

**Comment by gbdavidx** [comment]
how do you stop the service if it isnt running?
