### ISSUE TITLE
unhandled promise error

### ISSUE THREAD

**Issue by B-Hartley** [mKeRix/room-assistant#135]
**Describe the bug**
5 nodes running for a couple of days.
Stopped one and restarted it with -v

Got this error:
```

[Nest] 30279   - 03/09/2020, 8:45:49 PM   [HomeAssistantService] Sending new attributes {"distance":3.2,"lastUpdatedAt":"2020-03-09T20:45:49.149Z"} for room-assistant-bluetooth-classic-8c-86-1e-ce-6f-ab
(node:30279) UnhandledPromiseRejectionWarning: Error: client disconnecting
    at MqttClient._checkDisconnecting (/opt/nodejs/lib/node_modules/room-assistant/node_modules/mqtt/lib/client.js:368:16)
    at MqttClient.publish (/opt/nodejs/lib/node_modules/room-assistant/node_modules/mqtt/lib/client.js:408:12)
    at Promise (/opt/nodejs/lib/node_modules/room-assistant/node_modules/async-mqtt/index.js:30:31)
    at new Promise (<anonymous>)
    at AsyncClient.publish (/opt/nodejs/lib/node_modules/room-assistant/node_modules/async-mqtt/index.js:29:12)
    at _.debounce.attributes (/opt/nodejs/lib/node_modules/room-assistant/dist/integrations/home-assistant/home-assistant.service.js:129:33)
    at invokeFunc (/opt/nodejs/lib/node_modules/room-assistant/node_modules/lodash/lodash.js:10333:23)
    at trailingEdge (/opt/nodejs/lib/node_modules/room-assistant/node_modules/lodash/lodash.js:10382:18)
    at Timeout.timerExpired [as _onTimeout] (/opt/nodejs/lib/node_modules/room-assistant/node_modules/lodash/lodash.js:10370:18)
    at ontimeout (timers.js:436:11)
(node:30279) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30279) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To reproduce**
not sure I can yet....

can supply config if required, or it is the other bug.
 - room-assistant version: [e.g. 2.1.1]
 - installation type: Node JS
 - hardware: Raspberry Pi Zero W
 - OS:raspbian

clients are all iPhones of various model.

**Comment by mKeRix** [comment]
Did it happen while shutting down or after starting the new instance?
