### ISSUE TITLE
No heatmap, canvas dependency won't install (Raspberry pi 3) 

### ISSUE THREAD

**Issue by shlagwuk** [mKeRix/room-assistant#207]
**Describe the bug**
No heatmap is created with gridEye bacause canvas won't install.

**Relevant logs**
```
pi@salon:~/room-assistant $ sudo room-assistant -v
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
6/2/2020, 17:15:57 - info - IntegrationsModule: Loading integrations: home-assistant, grid-eye, gpio
6/2/2020, 17:15:58 - info - NestFactory: Starting Nest application...
[Nest] 12472   - 06/02/2020, 17:16:04   [ThermopileOccupancyService] Cannot find module 'canvas'
Require stack:
- /usr/lib/node_modules/room-assistant/dist/integrations/thermopile/thermopile-occupancy.service.js
- /usr/lib/node_modules/room-assistant/dist/integrations/grid-eye/grid-eye.service.js
- /usr/lib/node_modules/room-assistant/dist/integrations/grid-eye/grid-eye.module.js
- /usr/lib/node_modules/room-assistant/dist/integrations/integrations.module.js
- /usr/lib/node_modules/room-assistant/dist/app.module.js
- /usr/lib/node_modules/room-assistant/dist/main.js
- /usr/lib/node_modules/room-assistant/bin/room-assistant.js
Error: Cannot find module 'canvas'
Require stack:
- /usr/lib/node_modules/room-assistant/dist/integrations/thermopile/thermopile-occupancy.service.js
- /usr/lib/node_modules/room-assistant/dist/integrations/grid-eye/grid-eye.service.js
- /usr/lib/node_modules/room-assistant/dist/integrations/grid-eye/grid-eye.module.js
- /usr/lib/node_modules/room-assistant/dist/integrations/integrations.module.js
- /usr/lib/node_modules/room-assistant/dist/app.module.js
- /usr/lib/node_modules/room-assistant/dist/main.js
- /usr/lib/node_modules/room-assistant/bin/room-assistant.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/node_modules/room-assistant/dist/integrations/thermopile/thermopile-occupancy.service.js:31:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
```
**And latter:** 

`6/2/2020, 17:16:07 - warn - GridEyeService: Heatmap is unavailable due to the canvas dependency not being installed
`

**When I try to install canvas, I get:**

```
pi@salon:~/room-assistant $ npm i canvas --save

> canvas@2.6.1 install /home/pi/room-assistant/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-linux-glibc-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@12.17.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/pi/room-assistant/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
In file included from ../src/backend/Backend.h:6,
                 from ../src/backend/Backend.cc:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
In file included from ../src/backend/Backend.h:6,
                 from ../src/backend/ImageBackend.h:3,
                 from ../src/backend/ImageBackend.cc:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
In file included from ../src/backend/Backend.h:6,
                 from ../src/backend/PdfBackend.h:3,
                 from ../src/backend/PdfBackend.cc:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
In file included from ../src/backend/Backend.h:6,
                 from ../src/backend/SvgBackend.h:3,
                 from ../src/backend/SvgBackend.cc:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o
../src/bmp/BMPParser.cc: In member function ‘void BMPParser::Parser::parse(uint8_t*, int, uint8_t*)’:
../src/bmp/BMPParser.cc:189:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
   E(ptr - data > imgdOffset, "image data overlaps with another structure");
     ~~~~~~~~~~~^~~~~~~~~~~~
../src/bmp/BMPParser.cc:10:25: note: in definition of macro ‘E’
 #define E(cond, msg) if(cond) return setErr(msg)
                         ^~~~
../src/bmp/BMPParser.cc:204:27: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
   E(ptr - data + imgdSize > len, "not enough image data");
     ~~~~~~~~~~~~~~~~~~~~~~^~~~~
../src/bmp/BMPParser.cc:10:25: note: in definition of macro ‘E’
 #define E(cond, msg) if(cond) return setErr(msg)
                         ^~~~
  CXX(target) Release/obj.target/canvas/src/Backends.o
In file included from ../src/backend/Backend.h:6,
                 from ../src/Backends.h:3,
                 from ../src/Backends.cc:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/backend/Backend.h:6,
                 from ../src/Canvas.h:5,
                 from ../src/Canvas.cc:3:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::ToBuffer(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:415:26: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘unsigned int’} [-Wsign-compare]
     if (canvas->nBytes() > node::Buffer::kMaxLength) {
         ~~~~~~~~~~~~~~~~~^~~~~~
../src/Canvas.cc:479:79: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     uv_queue_work(uv_default_loop(), req, ToPngBufferAsync, (uv_after_work_cb)ToBufferAsyncAfter);
                                                                               ^~~~~~~~~~~~~~~~~~
../src/Canvas.cc:520:80: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     uv_queue_work(uv_default_loop(), req, ToJpegBufferAsync, (uv_after_work_cb)ToBufferAsyncAfter);
                                                                                ^~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
In file included from ../src/CanvasGradient.h:5,
                 from ../src/CanvasGradient.cc:3:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
In file included from ../src/CanvasPattern.h:6,
                 from ../src/CanvasPattern.cc:3:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
In file included from ../src/backend/Backend.h:6,
                 from ../src/Canvas.h:5,
                 from ../src/CanvasRenderingContext2d.h:6,
                 from ../src/CanvasRenderingContext2d.cc:3:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/closure.o
In file included from ../src/backend/Backend.h:6,
                 from ../src/Canvas.h:5,
                 from ../src/closure.h:5,
                 from ../src/closure.cc:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
In file included from ../src/Image.h:8,
                 from ../src/Image.cc:3:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/ImageData.o
In file included from ../src/ImageData.h:5,
                 from ../src/ImageData.cc:3:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
  CXX(target) Release/obj.target/canvas/src/init.o
In file included from ../src/backend/Backend.h:6,
                 from ../src/Backends.h:3,
                 from ../src/init.cc:17:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../../nan/nan.h:56,
                 from ../src/backend/Backend.h:6,
                 from ../src/Backends.h:3,
                 from ../src/init.cc:17:
../src/init.cc: At global scope:
/home/pi/.cache/node-gyp/12.17.0/include/node/node.h:608:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/12.17.0/include/node/node.h:642:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/init.cc:88:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(canvas, init);
 ^~~~~~~~~~~
  CXX(target) Release/obj.target/canvas/src/register_font.o
  SOLINK_MODULE(target) Release/obj.target/canvas.node
  COPY Release/canvas.node
make: Leaving directory '/home/pi/room-assistant/node_modules/canvas/build'
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/room-assistant/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/room-assistant/package.json'
npm WARN room-assistant No description
npm WARN room-assistant No repository field.
npm WARN room-assistant No README data
npm WARN room-assistant No license field.

+ canvas@2.6.1
added 1 package from 4 contributors and audited 115 packages in 184.326s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**"npm ls" gives:**

```
pi@salon:~/room-assistant $ npm ls
/home/pi/room-assistant
└─┬ canvas@2.6.1
  ├── nan@2.14.1
  ├─┬ node-pre-gyp@0.11.0
  │ ├── detect-libc@1.0.3
  │ ├─┬ mkdirp@0.5.5
  │ │ └── minimist@1.2.5
  │ ├─┬ needle@2.5.0
  │ │ ├─┬ debug@3.2.6
  │ │ │ └── ms@2.1.2
  │ │ ├─┬ iconv-lite@0.4.24
  │ │ │ └── safer-buffer@2.1.2
  │ │ └── sax@1.2.4
  │ ├─┬ nopt@4.0.3
  │ │ ├── abbrev@1.1.1
  │ │ └─┬ osenv@0.1.5
  │ │   ├── os-homedir@1.0.2
  │ │   └── os-tmpdir@1.0.2
  │ ├─┬ npm-packlist@1.4.8
  │ │ ├─┬ ignore-walk@3.0.3
  │ │ │ └─┬ minimatch@3.0.4
  │ │ │   └─┬ brace-expansion@1.1.11
  │ │ │     ├── balanced-match@1.0.0
  │ │ │     └── concat-map@0.0.1
  │ │ ├─┬ npm-bundled@1.1.1
  │ │ │ └── npm-normalize-package-bin@1.0.1 deduped
  │ │ └── npm-normalize-package-bin@1.0.1
  │ ├─┬ npmlog@4.1.2
  │ │ ├─┬ are-we-there-yet@1.1.5
  │ │ │ ├── delegates@1.0.0
  │ │ │ └─┬ readable-stream@2.3.7
  │ │ │   ├── core-util-is@1.0.2
  │ │ │   ├── inherits@2.0.4 deduped
  │ │ │   ├── isarray@1.0.0
  │ │ │   ├── process-nextick-args@2.0.1
  │ │ │   ├── safe-buffer@5.1.2 deduped
  │ │ │   ├─┬ string_decoder@1.1.1
  │ │ │   │ └── safe-buffer@5.1.2 deduped
  │ │ │   └── util-deprecate@1.0.2
  │ │ ├── console-control-strings@1.1.0
  │ │ ├─┬ gauge@2.7.4
  │ │ │ ├── aproba@1.2.0
  │ │ │ ├── console-control-strings@1.1.0 deduped
  │ │ │ ├── has-unicode@2.0.1
  │ │ │ ├── object-assign@4.1.1
  │ │ │ ├── signal-exit@3.0.3
  │ │ │ ├─┬ string-width@1.0.2
  │ │ │ │ ├── code-point-at@1.1.0
  │ │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
  │ │ │ │ │ └── number-is-nan@1.0.1
  │ │ │ │ └── strip-ansi@3.0.1 deduped
  │ │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ │ └── ansi-regex@2.1.1
  │ │ │ └─┬ wide-align@1.1.3
  │ │ │   └── string-width@1.0.2 deduped
  │ │ └── set-blocking@2.0.0
  │ ├─┬ rc@1.2.8
  │ │ ├── deep-extend@0.6.0
  │ │ ├── ini@1.3.5
  │ │ ├── minimist@1.2.5 deduped
  │ │ └── strip-json-comments@2.0.1
  │ ├─┬ rimraf@2.7.1
  │ │ └─┬ glob@7.1.6
  │ │   ├── fs.realpath@1.0.0
  │ │   ├─┬ inflight@1.0.6
  │ │   │ ├── once@1.4.0 deduped
  │ │   │ └── wrappy@1.0.2 deduped
  │ │   ├── inherits@2.0.4
  │ │   ├── minimatch@3.0.4 deduped
  │ │   ├── once@1.4.0 deduped
  │ │   └── path-is-absolute@1.0.1
  │ ├── semver@5.7.1
  │ └─┬ tar@4.4.13
  │   ├── chownr@1.1.4
  │   ├─┬ fs-minipass@1.2.7
  │   │ └── minipass@2.9.0 deduped
  │   ├─┬ minipass@2.9.0
  │   │ ├── safe-buffer@5.1.2 deduped
  │   │ └── yallist@3.1.1 deduped
  │   ├─┬ minizlib@1.3.3
  │   │ └── minipass@2.9.0 deduped
  │   ├── mkdirp@0.5.5 deduped
  │   ├── safe-buffer@5.1.2
  │   └── yallist@3.1.1
  └─┬ simple-get@3.1.0
    ├─┬ decompress-response@4.2.1
    │ └── mimic-response@2.1.0
    ├─┬ once@1.4.0
    │ └── wrappy@1.0.2
    └── simple-concat@1.0.0

pi@salon:~/room-assistant $ 
```

**"npm ls installed" gives:**

```
pi@salon:~/room-assistant $ npm ls installed
/home/pi/room-assistant
└── (empty)

pi@salon:~/room-assistant $ 
```

**Relevant configuration**
Deployed with ansible with this hosts.yml (bluetooth is commented, it's another story)
```all:
  hosts:
    'salon.local':
      room_assistant_config:
        global:
          integrations:
            - homeAssistant
            #- bluetoothClassic
            - gridEye
            - gpio
        gridEye:
          deltaThreshold: 2
          heatmap:
            minTemperature: 16
            maxTemperature: 30
            rotation: 180
        gpio:
          binarySensors:
            - name: Salon Motion Sensor
              pin: 14
              deviceClass: motion
    'chambre.local':
    'cuisine.local':
    'bureau.local':
  vars:
    room_assistant_version: 2.8.1
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          #- bluetoothClassic
      homeAssistant:
        mqttUrl: mqtt://192.168.1.100:1883
      #bluetoothClassic:
      #  interval: 3
      #  addresses:
      #    - '18:55:E3:99:8E:73'
```

**Environment**
 - room-assistant version: 2.8.1
 - installation type: NodeJS
 - hardware: Raspberry Pi 3, 3x Raspberry Pi Zero
 - OS: raspbian lite

**Comment by mKeRix** [comment]
You need some additional system packages and to re-run the room-assistant installation to also compile the `canvas` dependency. To do this just run the two commands in the ["Running with NodeJS"](https://www.room-assistant.io/integrations/grid-eye.html#requirements) requirements section of the integration.

```bash
sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
sudo npm i --global --unsafe-perm room-assistant
```

While reading I realized we could make the log message a bit more clear on this though.

**Comment by shlagwuk** [comment]
Thanks! I believed deploying with Ansible would do the trick… 

`sudo npm i --global --unsafe-perm room-assistant` was what I was missing…

**Comment by mKeRix** [comment]
In theory it should have, at least if you're on the newest version of the ansible-playbooks repository. But I also noticed issues with Ansible not re-checking room-assistant installations unless the version is specifically changed recently. It's something I wanted to look into sometime in the future.

Glad that this solved it for you!

**Comment by adiljahouh** [comment]
> In theory it should have, at least if you're on the newest version of the ansible-playbooks repository. But I also noticed issues with Ansible not re-checking room-assistant installations unless the version is specifically changed recently. It's something I wanted to look into sometime in the future.
> 
> Glad that this solved it for you!

Im having a similar issue but in docker? The only error i receive is "error - GridEyeService: Heatmaps cannot be rendered since the required dependencies aren't available. more info..." with a link back to the requirements on the RA grideye guide. The sensor is shown when calling `i2cdetect` on the Pi. Any help would be appreciated.
