### ISSUE TITLE
TypeError: config_1.default.get(...).map is not a function

### ISSUE THREAD

**Issue by blakemiddleton** [mKeRix/room-assistant#220]
```
TypeError: config_1.default.get(...).map is not a function
    at Object.<anonymous> (/opt/nodejs/lib/node_modules/room-assistant/dist/app.module.js:28:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/nodejs/lib/node_modules/room-assistant/dist/main.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

I get this error when running Room Assistant for the first time.

**Comment by mKeRix** [comment]
Could you post the config that you used? I strongly suspect that there is a formatting error in there.
