### ISSUE TITLE
gyp: Undefined variable openssl_config_path in binding.gyp while trying to load binding.gyp  

### ISSUE THREAD

**Issue by idfxken** [mKeRix/room-assistant#34]
When trying to install room-assistant on odroid c2  debian stretch, i ran into this, no idea how to fix it, happens with version 0.8 and 0.9

oot@domodroid:/opt/room-assistant# npm install

> bignum@0.11.0 install /opt/room-assistant/node_modules/bignum
> node-gyp configure build

gyp: Undefined variable openssl_config_path in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.14.79-odroidc2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /opt/room-assistant/node_modules/bignum
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bignum@0.11.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.11.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Any ideas?

**Comment by mKeRix** [comment]
nfarina/homebridge#566 seems to be the same problem - this is related to a dependency of room-assistant, not the project itself. The most suggested answer over there seems to be running `sudo apt-get install libavahi-compat-libdnssd-dev`.
