### ISSUE TITLE
Hass.io

### ISSUE THREAD

**Issue by grantalewis** [mKeRix/room-assistant#36]
I'd love to try this out. Any thoughts on creating an add-on for Hass.io users?

https://home-assistant.io/hassio/installing_third_party_addons/

**Comment by mKeRix** [comment]
I will try and get this accepted into the hassio community addon repository, but it may take 2 or 3 weeks until I can actually work on that (exams are keeping me busy).

Sorry to keep you waiting!

**Comment by grantalewis** [comment]
Thanks!

**Comment by stickystyle** [comment]
@mKeRix You don't have to get it listed in any specific repository, you can create your own config.json file in this github repo and we can utilize it directly.

https://home-assistant.io/developers/hassio/addon_development/

**Comment by mKeRix** [comment]
I spent a couple hours trying to figure this out today - and I still haven't got it working. I think my new Dockerfile should be correct for Hass.io usage, but I'm running into issues with the node dependencies. Some libraries won't compile in the alpine containers and I can't seem to find the missing libraries.

I have to put this on ice for a while, I'll take another look at this in the future. My current idea is moving away from the alpine base images proposed by all the examples, because then I can get around all the dependency issues. Or someone else with more hass.io know-how comes along. Sorry. :(

**Comment by escoand** [comment]
Is there anything code in this repo we can use for further trying?

**Comment by mKeRix** [comment]
I just uploaded my local stash to the `hassio` branch: https://github.com/mKeRix/room-assistant/tree/hassio

**Comment by escoand** [comment]
Got it working: https://github.com/mKeRix/room-assistant/pull/50

**Comment by grantalewis** [comment]
Nice! Great work!

**Comment by mKeRix** [comment]
Quick update: I sat down and played with this stuff for a bit, but currently I'm stuck at an issue with Travis - the arm images get stuck in the build process (just freeze, no error).

It works locally though, so possibly I'll just have to complete the hass.io images manually.

**Comment by jptrsn** [comment]
Any update on the progress of this? I'd love to get room assistant running on my pi 3 as well, since I've already got the hardware and it would free up a pi zero for a different room.

**Comment by escoand** [comment]
It's already working. Download the hassio, put it in a subdirectory of addons and remove the line with image. Then you should see the room-assistant add-on in the web interface.

**Comment by jptrsn** [comment]
It took me a little searching to find the right line to remove. It's in the base directory config.json file, [here](https://github.com/mKeRix/room-assistant/blob/hassio/config.json#L14).

@mKeRix would it be okay to make a pull request against the readme.md file for this branch? I would be happy to add it as a sub-section, unless there are imminent plans for publishing.

**Comment by escoand** [comment]
Yes, I've feared it wasn't exactly enough but it was late and I was tired. :-)
Good that you were able to find it after all...

**Comment by escoand** [comment]
I've error messages when enabling ble scanning:
```
Error: Cannot find module '../build/Release/binding.node'
```

**Comment by escoand** [comment]
Where do they build the official addons? Maybe they we can have a look how they do it...

**Comment by escoand** [comment]
Can you please remove the image parameter of the config.json in the repo in the meanwhile? So everybody is able to install it by compiling locally.

**Comment by escoand** [comment]
Forget about it, its not working without all the other files...

**Comment by mKeRix** [comment]
Just a quick update: I've just started rewriting room-assistant from scratch, since the current code is somewhat messy. Hopefully I'll be able to fix these Hass.io issues on the way!

**Comment by escoand** [comment]
I'm not much familiar with node.js but is it really necessary to have nearly 600MB for just so less functionality?

```
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
mkerix/room-assistant      latest-rpi          79837e848605        2 months ago        579MB
```

**Comment by mKeRix** [comment]
No, definitely not - that image still utilizes old build processes that I want to redo in the new version. The hass.io versions of the image are around 100MB big, which is much more reasonable.

Speaking of which: **I deployed a new version of room-assistant to my Hass.io repository!** It uses my new rewritten software, which already includes console, mqtt, ble and ibeacon functionality. It installs and runs fine on my Hass.io Raspberry, but I don't have a Bluetooth antenna to check whether the ble output runs correctly. **Could anybody help me test this?**

Use this repo: https://github.com/mKeRix/hassio-repo

Configuration is similar and mostly self explanatory name wise. Only important change you have to note is that instead of putting `"enabled": true` everywhere you now need to specify the components you want in the services array, e.g. `["console", "mqtt", "ble"]`. The ibeacon component has been merged into the ble component.

**Comment by MatsNl** [comment]
Hi!

Also looking to try this out on Hassio (running rpi model 3). Running into 2 seemingly unrelated issues:

On the repo: I cannot add it as the schema in config file appears to be wrong:
```
WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/git/6e66619d/room-assistant/config.json: expected string or buffer @ data['schema']['gpio']['ports'][0]. Got {'channel': 'str', 'pin': 'int', 'retain': 'bool?'}
expected string or buffer @ data['schema']['shell']['commands'][0]. Got {'channel': 'str', 'command': 'str', 'cron': 'str', 'regexp': 'str?', 'number': 'bool?', 'retain': 'bool?'}
```

Building as local repo with removed schema also has issues:

- Config is reset to default after filling & saving
- More serious: build errors and dependencies being skipped in log?
```
gyp ERR! System Linux 4.4.50
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/room-assistant/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/room-assistant/node_modules/usb/src/binding" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd /room-assistant/node_modules/usb
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/room-assistant/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/room-assistant/node_modules/usb/src/binding --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/room-assistant/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.4.50
node-pre-gyp ERR! command "/usr/bin/node" "/room-assistant/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /room-assistant/node_modules/usb
node-pre-gyp ERR! node -v v8.9.3
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/room-assistant/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/room-assistant/node_modules/usb/src/binding --napi_version=1 --node_abi_napi=napi' (1)
> bluetooth-hci-socket@0.5.1 install /room-assistant/node_modules/bluetooth-hci-socket
> node-gyp rebuild
make: Entering directory '/room-assistant/node_modules/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
../src/BluetoothHciSocket.cpp: In member function 'void BluetoothHciSocket::poll()':
../src/BluetoothHciSocket.cpp:251:95: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                                               ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../nan/nan.h:950:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/BluetoothHciSocket.cpp: In member function 'void BluetoothHciSocket::emitErrnoError()':
../src/BluetoothHciSocket.cpp:275:72: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);
                                                                        ^
In file included from /root/.node-gyp/8.9.3/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.3/include/node/node.h:63,
                 from /root/.node-gyp/8.9.3/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/root/.node-gyp/8.9.3/include/node/v8.h:3832:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/8.9.3/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/BluetoothHciSocket.cpp:282:93: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                                             ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../nan/nan.h:950:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/room-assistant/node_modules/bluetooth-hci-socket/build'
> epoll@2.0.1 install /room-assistant/node_modules/epoll
> node-gyp rebuild
make: Entering directory '/room-assistant/node_modules/epoll/build'
  CXX(target) Release/obj.target/epoll/src/epoll.o
  SOLINK_MODULE(target) Release/obj.target/epoll.node
  COPY Release/epoll.node
make: Leaving directory '/room-assistant/node_modules/epoll/build'
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN moleculer-web@0.8.0 requires a peer of moleculer@>= 0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN room-assistant@1.0.0 No repository field.
npm WARN room-assistant@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.3.2 (node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.3.2 install: node-pre-gyp install --fallback-to-build
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
+ prom-client@11.1.1
+ mqtt@2.18.2
+ moleculer-web@0.8.0
+ noble@1.9.1
+ onoff@3.1.0
added 142 packages in 158.679s
[2018-07-10T07:40:04.721Z] INFO  local-room-assistant-372/BROKER: Moleculer v0.12.8 is starting...
[2018-07-10T07:40:04.736Z] INFO  local-room-assistant-372/BROKER: Node ID: local-room-assistant-372
[2018-07-10T07:40:04.738Z] INFO  local-room-assistant-372/BROKER: Namespace: <not defined>
[2018-07-10T07:40:04.741Z] INFO  local-room-assistant-372/REGISTRY: Strategy: RoundRobinStrategy
[2018-07-10T07:40:04.787Z] INFO  local-room-assistant-372/REGISTRY: '$node' service is registered.
[2018-07-10T07:40:05.235Z] INFO  local-room-assistant-372/REGISTRY: 'api' service is registered.
[2018-07-10T07:40:05.242Z] INFO  local-room-assistant-372/API: Register route to '/'
[2018-07-10T07:40:05.249Z] INFO  local-room-assistant-372/API:   Alias: GET /metrics -> prometheus.metrics
[2018-07-10T07:40:05.250Z] INFO  local-room-assistant-372/API: API Gateway created!
[2018-07-10T07:40:05.390Z] INFO  local-room-assistant-372/REGISTRY: 'ble' service is registered.
[2018-07-10T07:40:05.397Z] INFO  local-room-assistant-372/REGISTRY: 'console' service is registered.
[2018-07-10T07:40:05.428Z] INFO  local-room-assistant-372/REGISTRY: 'gpio' service is registered.
[2018-07-10T07:40:05.687Z] INFO  local-room-assistant-372/REGISTRY: 'mqtt' service is registered.
[2018-07-10T07:40:06.144Z] INFO  local-room-assistant-372/REGISTRY: 'prometheus' service is registered.
[2018-07-10T07:40:06.427Z] INFO  local-room-assistant-372/REGISTRY: 'shell' service is registered.
[2018-07-10T07:40:06.441Z] INFO  local-room-assistant-372/BROKER: ServiceBroker with 8 service(s) is started successfully.
[2018-07-10T07:40:06.468Z] INFO  local-room-assistant-372/API: API Gateway listening on http://0.0.0.0:3000 

```

**Comment by mKeRix** [comment]
@MatsNl you can ignore the errors, the failing usb bindings module is optional.

As far as the schema goes: the current version in my Hass.io repo is running the rewritten alpha of room-assistant, which has a slightly different schema than described in the current README. I'm working on updating the configuration, until then here is an example for how you configure gpio and shell:

```json
{
  "gpio": {
    "ports": [
        {
          "channel": "channel-to-post-in",
          "pin": 4,
          "retain": true
        }
    ]
  },
  "shell": {
    "commands": [
        {
          "channel": "channel-to-post-in",
          "command": "echo abc",
          "cron": "0 * * * * *",
          "regexp": "optional-regex-syntax",
          "number": false,
          "retain": false
        }
    ]
  }
}
`
``

The explanation for the options can be found in the current docs mostly, as the logic is similar. Only differences are that GPIO does not need to be polled anymore (reacts on changes automatically) and shell commands run using a cron schema with 6 stars (so * on each would mean every second). The GPIO component now also uses different pin numbering (BCM).

I fixed the schema issue, but currently pushes to the branches are disabled. Until I release the official beta could you please grab the `rewrite` branch and build it locally? :)

**Comment by MatsNl** [comment]
No luck, when I press start once addon is installed, nothing happens and the config resets to default (empty) config.

also, gpio requires [""], otherwise the schema throws an error (i.e. cannot save, config not valid)

any suggestions? :)

**Comment by mKeRix** [comment]
Could you try re-adding my repo from above and trying the new image that should be available now? I re-enabled pushes for my alpha version and disabled the schema checks Hass.io does because they seem problematic together with the config schema we use. At least on my local raspi it worked when I checked it quickly.

**Comment by MatsNl** [comment]
Same issues, maybe the images arent refreshed before version number is incremented? I still get the config reset and error on gpio, also after deleting and reinstalling everything.. (actually did the re-add twice :) ) Any other thoughts?

after filling config, save, start, it returns to this:
`not a valid value for dictionary value @ data['options']. Got {'services': [], 'room': 'default-room', 'mqtt': {'url': 'mqtt://localhost', 'username': '', 'password': '', 'rejectUnauthorized': True}, 'ble': {'channel': 'room_presence', 'useAddress': False, 'whitelist': [], 'maxDistance': 0, 'updateFrequency': 0, 'processIBeacon': True, 'onlyIBeacon': False, 'majorMask': '0xFFFF', 'minorMask': '0xFFFF'}, 'gpio': [], 'shell': []}`

and then after putting [""] for gpio:

```
18-07-10 22:17:15 INFO (SyncWorker_15) [hassio.docker.interface] Remove docker mkerix/room-assistant-armhf with latest and 1.0.0-alpha
18-07-10 22:17:18 INFO (MainThread) [hassio.addons.addon] Remove Home-Assistant addon data folder /data/addons/data/6e66619d_room-assistant
18-07-10 22:17:54 INFO (MainThread) [hassio.addons.git] Remove custom addon repository https://github.com/mKeRix/hassio-repo
18-07-10 22:20:05 INFO (MainThread) [hassio.addons] Load addons: 62 all - 0 new - 1 remove
18-07-10 22:21:08 INFO (MainThread) [hassio.addons.git] Clone addon https://github.com/mKeRix/hassio-repo repository
18-07-10 22:21:11 INFO (MainThread) [hassio.addons] Load addons: 63 all - 1 new - 0 remove
18-07-10 22:21:23 INFO (MainThread) [hassio.addons.addon] Create Home-Assistant addon data folder /data/addons/data/6e66619d_room-assistant
18-07-10 22:21:23 INFO (SyncWorker_18) [hassio.docker.interface] Pull image mkerix/room-assistant-armhf tag 1.0.0-alpha.
18-07-10 22:24:50 INFO (SyncWorker_18) [hassio.docker.interface] Tag image mkerix/room-assistant-armhf with version 1.0.0-alpha as latest
18-07-10 22:28:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/security.py", line 56, in token_validation
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/utils.py", line 33, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/api/addons.py", line 156, in options
    body = await api_validate(addon_schema, request)
  File "/usr/lib/python3.6/site-packages/hassio/api/utils.py", line 92, in api_validate
    data = schema(data)
  File "/usr/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 587, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 379, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/lib/python3.6/site-packages/voluptuous/validators.py", line 204, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/lib/python3.6/site-packages/voluptuous/validators.py", line 249, in _exec
    return func(path, v)
  File "/usr/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 769, in validate_callable
    return schema(data)
  File "/usr/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/lib/python3.6/site-packages/voluptuous/validators.py", line 204, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/lib/python3.6/site-packages/voluptuous/validators.py", line 282, in _exec
    v = func(path, v)
  File "/usr/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 769, in validate_callable
    return schema(data)
  File "/usr/lib/python3.6/site-packages/hassio/addons/validate.py", line 214, in validate
    options[key] = _nested_validate_list(typ[0], value, key)
  File "/usr/lib/python3.6/site-packages/hassio/addons/validate.py", line 275, in _nested_validate_list
    c_options = _nested_validate_dict(typ, element, key)
  File "/usr/lib/python3.6/site-packages/hassio/addons/validate.py", line 287, in _nested_validate_dict
    for c_key, c_value in data_dict.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by mKeRix** [comment]
My bad, I forgot to upload my changes to the hassio-repo last night... shouldn't have done it in a hurry, sorry. 😅 Removing the add on, readding the repository and then installing it again pulls everything completely new, at least according to the logs. Unfortunately I am now seeing a different issue: the command it is using to launch the container is incorrect. I am a bit limited today with testing/fixing, but I want to get all this fixed and a beta out tomorrow. So could you maybe wait a day before continuing? :)

Fyi: The Alpha images are available for regular Docker too now, under the rewrite and rewrite-arm32 tags!

**Comment by mKeRix** [comment]
@MatsNl I actually found some additional time for debugging the Hass.io issue today and pushed a fix out. The version off my repo at least starts for me now. Would now appreciate any feedback on how GPIO and BLE services are running!

**Comment by MatsNl** [comment]
Cool,will give it a shot today! didn't have time yesterday unfortunately.

fyi, I 'm only able to test BLE in my setup
