### ISSUE TITLE
ERROR in Home Assistant log (when starting it) if using a Mi Flora sensor.

### ISSUE THREAD

**Issue by tunip** [mKeRix/room-assistant#374]
**Describe the bug**
When I start/restart Home Assistant I receive from all of my Xiaomi plant sensors (Mi Flora) the following message:
```
2020-12-01 20:46:44 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover_sensor when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'payload_available': 'online', 'payload_not_available': 'offline', 'name': 'schlafzimmer palme null', 'device': {'sw_version': '2.12.0', 'identifiers': '0000000000d2e4a1', 'name': 'bad', 'model': 'Raspberry Pi Zero W Rev 1.1', 'manufacturer': 'Raspberry Pi Foundation'}, 'unique_id': 'room-assistant-bad-schlafzimmer-palme-null', 'state_topic': 'room-assistant/sensor/bad-schlafzimmer-palme-null/state', 'json_attributes_topic': 'room-assistant/sensor/bad-schlafzimmer-palme-null/attributes', 'availability_topic': 'room-assistant/sensor/bad-schlafzimmer-palme-null/status', 'device_class': None, 'unit_of_measurement': 'µS/cm', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 83, in async_discover_sensor
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value is not allowed for dictionary value @ data['device_class']
```
**To reproduce**
Add a Mi Flora plant sensor to room-assistant and start/restart Home Assistant.

**Relevant logs**
```
12/1/2020, 9:00:00 PM - debug - HomeAssistantService: Sending new state 129 for room-assistant-bad-schlafzimmer-palme-null
12/1/2020, 9:00:02 PM - debug - XiaomiMiService: schlafzimmer palme: null: 129µS/cm
```

**Relevant configuration**
```
xiaomiMi:
  hciDeviceId: 0
  sensors:
    - name: schlafzimmer palme
      address: c47c8d6ab8ea
```

**Expected behavior**
I receive only 3 of 4 values from the plant sensors in Home Assistant. The fourth value "µS/cm" (conductivity or fertility) is missing.
The null in `room-assistant/sensor/bad-schlafzimmer-palme-null` should something like `room-assistant/sensor/bad-schlafzimmer-palme-conductivity` with no ERROR logs in Home Assistant.

**Environment**
 - room-assistant version: 2.12.0
 - installation type: NodeJS
 - hardware: Raspberry Pi Zero W
 - OS: Linux (Raspberry Pi OS)

**Additional context**
None

**Comment by mKeRix** [comment]
#362 was submitted to fix this issue (and improve some other things regarding Xiaomi). I plan to get this live in the coming days, I just need to do some small additional things for which I didn't have the time/energy yet. :)

**Comment by mKeRix** [comment]
This should now be fixed in the latest beta version!

**Comment by tunip** [comment]
Great work, I installed 2.13.0-beta.3 on one of my Raspberry Pi Zero's for testing. All sensors are listed now.

Some small visual improvement on the icons. Moistre could have the water-percent icon (mdi:water-percent) and conductivity the sprout icon (mdi: sprout)
<img width="332" alt="Bildschirmfoto 2020-12-06 um 23 00 35" src="https://user-images.githubusercontent.com/11404472/101294376-2456be80-3817-11eb-97c4-c039d8b2233d.png">

**Comment by PeteBa** [comment]
At present, room-assistant provides HA with a specific "device_class" field identifying whether a sensor is temperature, illuminance or humidity. This is provided in the mqtt discovery message and HA uses that to set the appropriate icon. Unfortunately, HA does not have a defined device_class for conductivity and moisture and hence the icons default to the eye. You can obviously set the icons manually on the HA side as needed.

In the short-term, this could be added on the room-assistant side by either hard-coding icons or providing additional configuration options. But the better long-term solution might be to try and get the moisture and conductivity device_classes defined in HA.
