### ISSUE TITLE
Docker Installation unable to start mdns and BLE does not seem to be discovering

### ISSUE THREAD

**Issue by jack-yen-by** [mKeRix/room-assistant#411]
**Describe the bug**
Tried using docker, getting failed to start mdns discovery, then tried just install as global npm module, issue doesn't exist.
Both docker and non-docker, I'm not able to discover my phone, it's as if the bluetooth is not starting to discover.

**To reproduce**
Followed docker-compose installation per documentation page. 

**Relevant logs**
```
12/16/2020, 4:50:51 AM - info - ConfigService: Loading configuration from /usr/local/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml
12/16/2020, 4:50:51 AM - error - ClusterService: Failed to start mdns discovery (dns service error: refused)
12/16/2020, 4:50:51 AM - info - NestApplication: Nest application successfully started
12/16/2020, 4:50:53 AM - info - ClusterService: controltower has been elected as leader
12/16/2020, 4:50:53 AM - info - EntitiesService: Refreshing entity states
```

**Expected behavior**
Expect mdns to start properly like non docker installation as well as BLE to function

**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - installation type: [e.g. NodeJS, Docker, Hass.io]
 - hardware: Asus PN50
 - OS: Ubuntu

**Comment by mKeRix** [comment]
Could you post your docker-compose file (with the config stripped of any credentials, MACs and so on)? I suspect that there is an issue with permissions for both of the problems that you describe. Did you also see the [requirements](https://www.room-assistant.io/integrations/bluetooth-low-energy.html#requirements) section of the BLE integration?

**Comment by mKeRix** [comment]
For the Docker install I also just had another idea... could you try adding the following to your docker-compose (under `room-assistant`, on the same level as `network_mode`):

```yaml
cap_add:
- NET_ADMIN
```

**Comment by jack-yen-by** [comment]
```
# Room Assistant
  room-assistant:
    image: mkerix/room-assistant:beta
    container_name: roomassistant
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    restart: always
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - $DOCKER_DIR/room-assistant/config:/room-assistant/config
```

```
bluetoothLowEnergy:
    tagOverrides:
        LONG-ID:
            name: iPhone
    whitelist:
    - LONG-ID
global:
    integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
    mqttOptions:
        password: null
        username: null
    mqttUrl: mqtt://192.168.1.xxx:1883
```

For both docker / nodejs installation, the cluster show up on mqtt without issue.
nodejs is able to discover additional clusters, whereas docker cannot due to that mdns failure. I did go through with the requirements page and install all that, still no luck for nodejs installation. One thing to note is that, this installation is on amd x64, where as the rest of the instances are pi0.

**Comment by jack-yen-by** [comment]
Here's a full verbose log for nodejs installation

```
12/16/2020, 4:01:01 PM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-low-energy
12/16/2020, 4:01:02 PM - info - NestFactory: Starting Nest application...
12/16/2020, 4:01:02 PM - info - InstanceLoader: AppModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: ConfigModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: HttpModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: ClusterModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: TerminusModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: BluetoothModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: ScheduleModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: EntitiesModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: BluetoothLowEnergyModule dependencies initialized
12/16/2020, 4:01:02 PM - info - InstanceLoader: StatusModule dependencies initialized
12/16/2020, 4:01:02 PM - info - RoutesResolver: EntitiesController {/entities}:
12/16/2020, 4:01:02 PM - info - RouterExplorer: Mapped {/entities, GET} route
12/16/2020, 4:01:02 PM - info - RoutesResolver: StatusController {/status}:
12/16/2020, 4:01:02 PM - info - RouterExplorer: Mapped {/status, GET} route
12/16/2020, 4:01:02 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.1.xxx:1883
12/16/2020, 4:01:02 PM - info - ConfigService: Loading configuration from /usr/local/lib/node_modules/room-assistant/dist/config/definitions/default.js, local.yml
12/16/2020, 4:01:02 PM - debug - EntitiesService: Adding new entity status-cluster-size
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Registering entity room-assistant-controltower-status-cluster-size under homeassistant/sensor/room-assistant/controltower-status-cluster-size/config
12/16/2020, 4:01:02 PM - debug - EntitiesService: Adding new entity status-cluster-leader
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Registering entity room-assistant-controltower-status-cluster-leader under homeassistant/sensor/room-assistant/controltower-status-cluster-leader/config
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new state 1 for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new state none for room-assistant-controltower-status-cluster-leader
12/16/2020, 4:01:02 PM - info - ClusterService: Starting mDNS advertisements and discovery
12/16/2020, 4:01:02 PM - info - NestApplication: Nest application successfully started
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["controltower"]} for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new attributes {"quorumReached":true} for room-assistant-controltower-status-cluster-leader
12/16/2020, 4:01:02 PM - info - ClusterService: Added 192.168.1.41:6425 to the cluster with id masterbedroom
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new state 2 for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["masterbedroom","controltower"]} for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - info - ClusterService: Added 192.168.1.32:6425 to the cluster with id garage
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new state 3 for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["masterbedroom","garage","controltower"]} for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - info - ClusterService: Added 192.168.1.56:6425 to the cluster with id livingroom
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new state 4 for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["masterbedroom","garage","livingroom","controltower"]} for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - info - ClusterService: Added 192.168.1.53:6425 to the cluster with id diningroom
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new state 5 for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["masterbedroom","garage","livingroom","diningroom","controltower"]} for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - info - ClusterService: Added 192.168.1.86:6425 to the cluster with id room1
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new state 6 for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:02 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["masterbedroom","garage","livingroom","diningroom","room1","controltower"]} for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:03 PM - info - ClusterService: Added 192.168.1.36:6425 to the cluster with id workarea
12/16/2020, 4:01:03 PM - debug - HomeAssistantService: Sending new state 7 for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:03 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["masterbedroom","garage","livingroom","diningroom","room1","workarea","controltower"]} for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:03 PM - info - ClusterService: Added 192.168.1.58:6425 to the cluster with id kitchen
12/16/2020, 4:01:03 PM - debug - HomeAssistantService: Sending new state 8 for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:03 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["masterbedroom","garage","livingroom","diningroom","room1","workarea","kitchen","controltower"]} for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:03 PM - info - ClusterService: Added 192.168.1.76:6425 to the cluster with id frontlivingroom
12/16/2020, 4:01:03 PM - debug - HomeAssistantService: Sending new state 9 for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:03 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["masterbedroom","garage","livingroom","diningroom","room1","workarea","kitchen","frontlivingroom","controltower"]} for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:03 PM - info - ClusterService: Added 192.168.1.31:6425 to the cluster with id smallbedroom
12/16/2020, 4:01:03 PM - debug - HomeAssistantService: Sending new state 10 for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:03 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["masterbedroom","garage","livingroom","diningroom","room1","workarea","kitchen","frontlivingroom","smallbedroom","controltower"]} for room-assistant-controltower-status-cluster-size
12/16/2020, 4:01:03 PM - debug - EntitiesService: Adding new entity ble-LONGID-tracker
12/16/2020, 4:01:03 PM - info - HomeAssistantService: Device tracker requires manual setup in Home Assistant with topic: room-assistant/device_tracker/ble-LONGID-tracker/state
12/16/2020, 4:01:03 PM - debug - EntitiesService: Adding new entity ble-LONGID
12/16/2020, 4:01:03 PM - debug - HomeAssistantService: Registering entity room-assistant-ble-LONGID under homeassistant/sensor/room-assistant/LONGID/config
```

Generally it should have something like this for other pi0 instances where as this one just stuck at the above log and nothing else.
info - BluetoothLowEnergyService: Discovered new BLE peripheral

**Comment by hugalafutro** [comment]
This is strange as I literally migrated from node install to a docker and "it just works". For reference this is my docker-compose.yml
```
version: '3'
services:
  room-assistant:
    container_name: room-assistant
    image: mkerix/room-assistant
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./config:/room-assistant/config
    restart: unless-stopped
```
the local.yml I just copied in to config/ from the node install

**Comment by jack-yen-by** [comment]
@hugalafutro what hardware / OS are you using?

**Comment by hugalafutro** [comment]
raspberry pi zero W with raspbian (i think buster is current?)

**Comment by hugalafutro** [comment]
log from running container:
```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
12/16/2020, 11:39:05 PM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic
12/16/2020, 11:39:13 PM - info - NestFactory: Starting Nest application...
12/16/2020, 11:39:14 PM - info - InstanceLoader: AppModule dependencies initialized
12/16/2020, 11:39:14 PM - info - InstanceLoader: ConfigModule dependencies initialized
12/16/2020, 11:39:14 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
12/16/2020, 11:39:14 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
12/16/2020, 11:39:14 PM - info - InstanceLoader: HttpModule dependencies initialized
12/16/2020, 11:39:14 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
12/16/2020, 11:39:14 PM - info - InstanceLoader: ClusterModule dependencies initialized
12/16/2020, 11:39:14 PM - info - InstanceLoader: TerminusModule dependencies initialized
12/16/2020, 11:39:14 PM - info - InstanceLoader: BluetoothModule dependencies initialized
12/16/2020, 11:39:15 PM - info - InstanceLoader: ScheduleModule dependencies initialized
12/16/2020, 11:39:15 PM - info - InstanceLoader: EntitiesModule dependencies initialized
12/16/2020, 11:39:15 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
12/16/2020, 11:39:15 PM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
12/16/2020, 11:39:15 PM - info - InstanceLoader: StatusModule dependencies initialized
12/16/2020, 11:39:18 PM - info - RoutesResolver: EntitiesController {/entities}:
12/16/2020, 11:39:18 PM - info - RouterExplorer: Mapped {/entities, GET} route
12/16/2020, 11:39:18 PM - info - RoutesResolver: StatusController {/status}:
12/16/2020, 11:39:18 PM - info - RouterExplorer: Mapped {/status, GET} route
12/16/2020, 11:39:20 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.1.101:1883
12/16/2020, 11:39:20 PM - info - ConfigService: Loading configuration from /usr/local/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml
12/16/2020, 11:39:21 PM - info - ClusterService: Starting mDNS advertisements and discovery
12/16/2020, 11:39:21 PM - info - NestApplication: Nest application successfully started
12/16/2020, 11:39:42 PM - info - HomeAssistantService: Device tracker requires manual setup in Home Assistant with topic: room-assistant/device_tracker/bluetooth-classic-64-a2-f9-b8-98-ad-tracker/state
12/16/2020, 11:44:03 PM - error - BluetoothService: Command failed: hcitool -i hci0 cc "64:A2:F9:B8:98:AD" && hcitool -i hci0 rssi "64:A2:F9:B8:98:AD"
12/16/2020, 11:45:03 PM - error - BluetoothService: Command failed: hciconfig hci0 reset
/bin/sh: hciconfig: Operation not permitted
```

the 3 errors at the end are there constantly every few inutes even on node install I think it's because I got other stuff running there and the BT and Wifi are fighting as that is an issue on rpi zero I believe

**Comment by jack-yen-by** [comment]
I'm running on Ubuntu, AMD Ryzen 4500u. I'm not sure if it makes any difference though. I wonder if there's any difference. I assume it should support x64?

**Comment by hugalafutro** [comment]
Well no actually raspbian is 32bit (64bit is in beta) as rpi zero only has 512Mb ram :D

Maybe your case is related to using a cluster of room-assistant, I only use the single one

**Comment by member68** [comment]
This seems to happen in a non-docker installation as well. I installed my cluster using Ansible.

``` 
pi@pi-arbeitszimmer:~ $ room-assistant -v
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
12/21/2020, 5:24:57 PM - info - IntegrationsModule: Loading integrations: none
12/21/2020, 5:24:59 PM - info - NestFactory: Starting Nest application...
12/21/2020, 5:24:59 PM - info - InstanceLoader: AppModule dependencies initialized
12/21/2020, 5:24:59 PM - info - InstanceLoader: ConfigModule dependencies initialized
12/21/2020, 5:24:59 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
12/21/2020, 5:24:59 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
12/21/2020, 5:24:59 PM - info - InstanceLoader: HttpModule dependencies initialized
12/21/2020, 5:24:59 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
12/21/2020, 5:24:59 PM - info - InstanceLoader: ClusterModule dependencies initialized
12/21/2020, 5:24:59 PM - info - InstanceLoader: TerminusModule dependencies initialized
12/21/2020, 5:24:59 PM - info - InstanceLoader: ScheduleModule dependencies initialized
12/21/2020, 5:24:59 PM - info - InstanceLoader: EntitiesModule dependencies initialized
12/21/2020, 5:24:59 PM - info - InstanceLoader: StatusModule dependencies initialized
12/21/2020, 5:25:03 PM - info - RoutesResolver: EntitiesController {/entities}:
12/21/2020, 5:25:03 PM - info - RouterExplorer: Mapped {/entities, GET} route
12/21/2020, 5:25:04 PM - info - RoutesResolver: StatusController {/status}:
12/21/2020, 5:25:04 PM - info - RouterExplorer: Mapped {/status, GET} route
12/21/2020, 5:25:04 PM - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js
12/21/2020, 5:25:04 PM - warn - ConfigService: No configuration found in /home/pi/config
12/21/2020, 5:25:04 PM - debug - EntitiesService: Adding new entity status-cluster-size
12/21/2020, 5:25:04 PM - debug - EntitiesService: Adding new entity status-cluster-leader
12/21/2020, 5:25:04 PM - info - ClusterService: Starting mDNS advertisements and discovery
12/21/2020, 5:25:04 PM - info - NestApplication: Nest application successfully started
12/21/2020, 5:25:04 PM - info - ClusterService: pi-arbeitszimmer has been elected as leader
12/21/2020, 5:25:04 PM - info - EntitiesService: Refreshing entity states
12/21/2020, 5:25:04 PM - info - ClusterService: Added 10.0.0.85:6425 to the cluster with id pi-wohnzimmer
12/21/2020, 5:25:04 PM - info - ClusterService: Added 10.0.0.95:6425 to the cluster with id pi-kueche
12/21/2020, 5:25:04 PM - info - ClusterService: Added 10.0.0.86:6425 to the cluster with id pi-schlafzimmer
12/21/2020, 5:25:05 PM - info - ClusterService: Added 10.0.0.94:6425 to the cluster with id pi-bad
12/21/2020, 5:25:09 PM - error - ClusterService: dns service error: unknown
```

Config:
``` yaml
all:
  hosts:
    '10.0.0.80':
      room_assistant_config:
    '10.0.0.85':
      room_assistant_config:
    '10.0.0.86':
      room_assistant_config:
    '10.0.0.94':
      room_assistant_config:
    '10.0.0.95':
      room_assistant_config:
  vars:
    ansible_user: pi
    ansible_ssh_pass: [removed]
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: mqtt://nas:1883
        mqttOptions:
          username: [removed]
          password: [removed]
      bluetoothClassic:
        minRssi: -20
        addresses:
          - '[removed]'
      bluetoothLowEnergy:
        whitelist:
          - [removed]
        tagoverrides:
          [removed]:
            name: [removed]

**Comment by meme1337** [comment]
Did you guys manage to make it work with Docker?
I'm in the same situation, logs show this and no updates:

```
12/29/2020, 8:17:44 AM - info - ConfigService: Loading configuration from /usr/local/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml
12/29/2020, 8:17:44 AM - error - ClusterService: Failed to start mdns discovery (dns service error: refused)
12/29/2020, 8:17:44 AM - info - NestApplication: Nest application successfully started
12/29/2020, 8:17:46 AM - info - ClusterService: rivendell has been elected as leader
12/29/2020, 8:17:46 AM - info - EntitiesService: Refreshing entity states
```

**Comment by boojew** [comment]
Yea, I have similar issues w/ the same config on docker on a RPI3
```
room-assistant_1  | 2/1/2021, 4:44:02 PM - info - RouterExplorer: Mapped {/status, GET} route
room-assistant_1  | 2/1/2021, 4:44:02 PM - info - RoutesResolver: PrometheusController {/metrics}:
room-assistant_1  | 2/1/2021, 4:44:02 PM - info - RouterExplorer: Mapped {/metrics, GET} route
room-assistant_1  | ls: /dev/disk/by-id/: No such file or directory
room-assistant_1  | 2/1/2021, 4:44:03 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.0.229:1883
room-assistant_1  | 2/1/2021, 4:44:03 PM - info - ConfigService: Loading configuration from /usr/local/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml
room-assistant_1  | 2/1/2021, 4:44:03 PM - info - ClusterService: Starting mDNS advertisements and discovery
room-assistant_1  | 2/1/2021, 4:44:03 PM - info - NestApplication: Nest application successfully started
room-assistant_1  | /usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:107
room-assistant_1  |         throw e;
room-assistant_1  |         ^
room-assistant_1  | 
room-assistant_1  | Error: ENODEV, No such device
room-assistant_1  |     at Hci.init (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:102:37)
room-assistant_1  |     at NobleBindings.init (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/bindings.js:111:13)
room-assistant_1  |     at /usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/noble.js:60:24
room-assistant_1  |     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
room-assistant_1  |   errno: 19,
room-assistant_1  |   code: 'ENODEV',
room-assistant_1  |   syscall: 'bind'
room-assistant_1  | }
room-assistant_room-assistant_1 exited with code 0

```

**Comment by boojew** [comment]
.. sigh seems I had bluetooth disabled. Solved for me

**Comment by bachoo786** [comment]
I have the same issue and my BLE devices cannot be discovered by Room Assistant on Home Assistant. Get this error 
`2/17/2021, 11:53:32 AM - error - ClusterService: Failed to start mdns discovery (dns service error: refused)`

**Comment by myhrmans** [comment]
Facing the same issue. Bluetooth is one and facing the same issue.

Current docker-compose:
` room-assistant:
    image: mkerix/room-assistant
    network_mode: host
    cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
    environment:
      NODE_CONFIG: >
        {
          "global": {
            "instanceName": "datarummet",
            "integrations": ["homeAssistant", "bluetoothClassic", "bluetoothLowEnergy"]
          },
        }`

**Comment by Rick-Git** [comment]
Having the same issues. 
Simular config like @myhrmans. Tried with and without cap_add. 

Keep getting

> 12/16/2020, 4:50:51 AM - info - ConfigService: Loading configuration from /usr/local/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml
12/16/2020, 4:50:51 AM - error - ClusterService: Failed to start mdns discovery (dns service error: refused)
12/16/2020, 4:50:51 AM - info - NestApplication: Nest application successfully started
12/16/2020, 4:50:53 AM - info - ClusterService: controltower has been elected as leader
12/16/2020, 4:50:53 AM - info - EntitiesService: Refreshing entity states

**Comment by BelgarionNL** [comment]
same. running it on a rpi 3B+ in docker using portainer.
