### ISSUE TITLE
Room-Assistant 2.12.0 not starting, throwing bind error

### ISSUE THREAD

**Issue by Will-wastelander** [mKeRix/room-assistant#447]
**Describe the bug**
I apologize if this is a configuration issue, but I have tried everything I can find to get it working, and I just can't. I even tried the example config, and got the same error. When configuring RA 2.12.0, I am unable to get it to start. 

**To reproduce**
Steps required to reproduce the issue.
Install, add configurations, and attempt to start.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:47:18] INFO: Setting up Home Assistant configuration
[22:47:18] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
1/11/2021, 10:47:20 PM - info - IntegrationsModule: Loading integrations: bluetooth-low-energy, bluetooth-classic, home-assistant
1/11/2021, 10:47:21 PM - info - NestFactory: Starting Nest application...
1/11/2021, 10:47:21 PM - info - InstanceLoader: AppModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: ConfigModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: HttpModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: ClusterModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: TerminusModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: BluetoothModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: ScheduleModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: EntitiesModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: BluetoothLowEnergyModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
1/11/2021, 10:47:21 PM - info - InstanceLoader: StatusModule dependencies initialized
1/11/2021, 10:47:22 PM - info - RoutesResolver: EntitiesController {/entities}:
1/11/2021, 10:47:22 PM - info - RouterExplorer: Mapped {/entities, GET} route
1/11/2021, 10:47:22 PM - info - RoutesResolver: StatusController {/status}:
1/11/2021, 10:47:22 PM - info - RouterExplorer: Mapped {/status, GET} route
1/11/2021, 10:47:22 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.x.x:1883
1/11/2021, 10:47:22 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
1/11/2021, 10:47:22 PM - info - ClusterService: Starting mDNS advertisements and discovery
1/11/2021, 10:47:22 PM - info - NestApplication: Nest application successfully started
/usr/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100
    this._deviceId = this._socket.bindRaw(deviceId);
                                  ^
Error: ENODEV, No such device
    at Hci.init (/usr/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
    at NobleBindings.init (/usr/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:78:13)
    at /usr/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 19,
  code: 'ENODEV',
  syscall: 'bind'
}
[cmd] /room-assistant/entrypoint.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: Tiki_Garage_BS
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
homeAssistant:
  mqttUrl: 'mqtt://192.168.x.x:1883'
  mqttOptions:
    username: XXXXXXXX
    password: XXXXXXXX
bluetoothLowEnergy:
  processIBeacon: true
  maxDistance: 4
  timeout: 5
  updateFrequency: 0
  whitelist:
    - BC7AXXXXXXXX
    - 8C83XXXXXXXX
  tagOverrides:
    8C83XXXXXXXX:
      name: Smart Watch
    BC7AXXXXXXXX:
      name: Note20
```
 Example config tried
```
global:
  instanceName: bedroom
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
```

**Expected behavior**
For it to start, and not throw an error.

**Environment**
 - room-assistant version: [2.12.0]
 - installation type: [HA Supervised (Docker)]
 - hardware: [Intel Pentium D]
 - OS: [Debian GNU/Linux 10 (buster) x86_64]

**Additional context**
I have attempted to locate documentation on proper setup, and I have been unable to find anything that had been able to help. If there is documentation that you would be able to provide, if it is a configuration issue. It would be GREATLY appreciated.

**Comment by mKeRix** [comment]
This error is thrown when it cannot find a Bluetooth adapter under the specified id, which by default is `0`. The host that you are running therefore needs a device called `hci0` to function. You can check the available devices with the `hciconfig` command (I think that is also available in the SSH add-on, otherwise use `bluetoothctl` and then `list`).

It is possible that the adapter is just under a different ID (then you would need to update the `hciDeviceId` in the config) or that Home Assistant OS isn't mounting the adapter correctly (for which you would need to open an issue at [home-assistant/operating-system](https://github.com/home-assistant/operating-system)).

**Comment by Will-wastelander** [comment]
@mKeRix I was previously told that a Bluetooth adapter was not needed, but
then after speaking with you on discord, I found out that one is needed.

I was under the impression, from speaking with others on another discord,
that I could use esp32 BLE to be the BLE devices.
