### ISSUE TITLE
TypeError: whitelist.includes is not a function

### ISSUE THREAD

**Issue by pblvsk** [mKeRix/room-assistant#47]
When starting app with whitelist added I get following:

```
> room-assistant@0.4.1 start /home/pi/room-assistant
> node index.js

                                            Starting Room Assistant...
                                            Connected to MQTT server
                                            Started console publisher
BLE scanner was initialized
/home/pi/room-assistant/components/ble.js:57
    if ((whitelist.length > 0 && whitelist.includes(id))
                                           ^

TypeError: whitelist.includes is not a function
    at BLEScanner._handlePacket (/home/pi/room-assistant/components/ble.js:57:44)
    at emitOne (events.js:77:13)
    at Noble.emit (events.js:169:7)
    at Noble.onDiscover (/home/pi/room-assistant/node_modules/noble/lib/noble.js:174:10)
    at emitMany (events.js:108:13)
    at emit (events.js:182:7)
    at NobleBindings.onDiscover (/home/pi/room-assistant/node_modules/noble/lib/hci-socket/bindings.js:174:10)
    at emitMany (events.js:108:13)
    at emit (events.js:182:7)
    at Gap.onHciLeAdvertisingReport (/home/pi/room-assistant/node_modules/noble/lib/hci-socket/gap.js:256:10)

npm ERR! room-assistant@0.4.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the room-assistant@0.4.1 start script.
npm ERR! This is most likely a problem with the room-assistant package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls room-assistant
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.70-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/room-assistant
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/room-assistant/npm-debug.log
npm ERR! not ok code 0
```

Config:

```
{
  "app": {
    "unsafe": false
  },
  "mqtt": {
    "enabled": true,
    "url": "mqtt://localhost",
    "username": "someusername",
    "password": "somepassword",
    "reject_unauthorized": true,
    "topic": "salon"
  },
  "console": {
    "enabled": true
  },
  "ble": {
    "enabled": true,
    "channel": "room_presence",
    "max_distance": 0,
    "blacklist": [],
    "whitelist": ["e69964bad240"],
    "use_mac": false,
    "system_noise": 0.01,
    "measurement_noise": 3,
    "update_frequency": 5
  },
  "ibeacon": {
    "enabled": false,
    "channel": "room_presence",
    "max_distance": 0,
    "blacklist": [],
    "whitelist": [],
    "system_noise": 0.01,
    "measurement_noise": 3,
    "major_mask": "0xFFFF",
    "minor_mask": "0xFFFF"
  },
  "temper": {
    "enabled": false,
    "channel": "temper",
    "interval": 60000,
    "scale": 1,
    "offset": 0
  },
  "gpio": {
    "enabled": false,
    "only_send_updates": true,
    "ports": [],
    "qos": 0,
    "retain": false
  },
  "shell": {
    "enabled": false,
    "commands": [],
    "qos": 0,
    "retain": false
  }
}
```

**Comment by mKeRix** [comment]
This is related to the nodejs/node#5715 ticket. Could you try [upgrading to the latest version of NodeJS](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)? You're still running on 4.8, current one is 8.10.

**Comment by pblvsk** [comment]
Hi @mKeRix,

that helped. It's quite odd as I already tried updating nodejs and I was just getting a different error. Anyway, now sorted!
