### ISSUE TITLE
Cant get it working on rasberry pi W } catch {

### ISSUE THREAD

**Issue by gbdavidx** [mKeRix/room-assistant#533]
**Describe the bug**
Fresh install, going through the steps, and i receive this when i type in room-assistant

pi@pioffice:~ $ room-assistant 
/usr/local/lib/node_modules/room-assistant/node_modules/update-notifier/index.js:58
			} catch {
			        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/room-assistant/bin/room-assistant.js:4:24)
pi@pioffice:~ $ 

**To reproduce**
get a rasberry pi w and install latest npm package

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
```

**Relevant configuration**
home-assistant in a vm running ubuntu

```yaml
```

**Expected behavior**

**Environment**
 - room-assistant version: [just downloaded today]
 - nodejs: [e.g. NodeJS, Docker, Hass.io]
 - Raspberry Pi Zero W,
 - Raspberry Pi OS with desktop

**Additional context**

**Comment by mKeRix** [comment]
This isn't really related to room-assistant per se, as the error is in one of the dependencies. Did you already try reinstalling room-assistant? Which version of NodeJS are you using?

**Comment by gbdavidx** [comment]
which dependancy?

**Comment by mKeRix** [comment]
`update-notifier` as it says in your error log. Which version of Node are you trying to run it on?
