### ISSUE TITLE
bluetooth_hci_socket.node & dns_sd_bindings.node complaining about the node version and service fails to start

### ISSUE THREAD

**Issue by danodemano** [mKeRix/room-assistant#605]
**Describe the bug**
Room Assistant fails to start

**To reproduce**
Attempt to start room assistant

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
Mar 17 15:55:47 octopi systemd[1]: Started room-assistant service.
Mar 17 15:55:48 octopi room-assistant[13527]: #033[31m[Nest] 13527   - #033[39m17/03/2021, 15:55:48   #033[38;5;3m[ClusterService] #033[39m#033[31mThe module '/usr/lib/node_modules/room-assistant/node_modules/mdns/build/Release/dns_sd_bindings.node'
Mar 17 15:55:48 octopi room-assistant[13527]: was compiled against a different Node.js version using
Mar 17 15:55:48 octopi room-assistant[13527]: NODE_MODULE_VERSION 72. This version of Node.js requires
Mar 17 15:55:48 octopi room-assistant[13527]: NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
Mar 17 15:55:48 octopi room-assistant[13527]: the module (for instance, using `npm rebuild` or `npm install`).#033[39m
Mar 17 15:55:48 octopi room-assistant[13527]: Error: The module '/usr/lib/node_modules/room-assistant/node_modules/mdns/build/Release/dns_sd_bindings.node'
Mar 17 15:55:48 octopi room-assistant[13527]: was compiled against a different Node.js version using
Mar 17 15:55:48 octopi room-assistant[13527]: NODE_MODULE_VERSION 72. This version of Node.js requires
Mar 17 15:55:48 octopi room-assistant[13527]: NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
Mar 17 15:55:48 octopi room-assistant[13527]: the module (for instance, using `npm rebuild` or `npm install`).
Mar 17 15:55:48 octopi room-assistant[13527]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
Mar 17 15:55:48 octopi room-assistant[13527]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Mar 17 15:55:48 octopi room-assistant[13527]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Mar 17 15:55:48 octopi room-assistant[13527]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Mar 17 15:55:48 octopi room-assistant[13527]:     at require (internal/modules/cjs/helpers.js:88:18)
Mar 17 15:55:48 octopi room-assistant[13527]:     at Object.<anonymous> (/usr/lib/node_modules/room-assistant/node_modules/mdns/lib/dns_sd.js:24:20)
Mar 17 15:55:48 octopi room-assistant[13527]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Mar 17 15:55:48 octopi room-assistant[13527]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Mar 17 15:55:48 octopi room-assistant[13527]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Mar 17 15:55:48 octopi room-assistant[13527]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Mar 17 15:55:49 octopi room-assistant[13527]: 17/03/2021, 15:55:49 - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-low-energy
Mar 17 15:55:50 octopi room-assistant[13527]: 17/03/2021, 15:55:50 - info - NestFactory: Starting Nest application...
Mar 17 15:55:50 octopi room-assistant[13527]: 17/03/2021, 15:55:50 - error - ExceptionHandler: The module '/usr/lib/node_modules/room-assistant/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
Mar 17 15:55:50 octopi room-assistant[13527]: was compiled against a different Node.js version using
Mar 17 15:55:50 octopi room-assistant[13527]: NODE_MODULE_VERSION 72. This version of Node.js requires
Mar 17 15:55:50 octopi room-assistant[13527]: NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
Mar 17 15:55:50 octopi room-assistant[13527]: the module (for instance, using `npm rebuild` or `npm install`).
Mar 17 15:55:50 octopi systemd[1]: room-assistant.service: Main process exited, code=exited, status=1/FAILURE
Mar 17 15:55:50 octopi systemd[1]: room-assistant.service: Failed with result 'exit-code'.
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
all:
  hosts:
    #Pi Zero Only RoomAssistant
    '192.168.9.230':
      ansible_user: pi
      ansible_password: <password>
      ansible_sudo_pass: <password>
      name: living_room
      instanceName: living_room
    #Pi Zero Only RoomAssistant
    '192.168.9.231':
      ansible_user: pi
      ansible_password: <password>
      ansible_sudo_pass: <password>
      name: den
      instanceName: den
    #Octoprint
    '192.168.9.33':
      ansible_user: pi
      ansible_password: <password>
      ansible_sudo_pass: <password>
      name: ante_chamber
      instanceName: ante_chamber
    #Genmon
    '192.168.9.219':
      ansible_user: pi
      ansible_password: <password>
      ansible_sudo_pass: <password>
      name: basement
      instanceName: basement
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        cluster:
          autoDiscovery: true
          port: 6425
        integrations:
          - homeAssistant
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: 'mqtt://192.168.9.200:1883'
      bluetoothLowEnergy:
        timeout: 10
        allowlist:
          - '426c7565436861726d426561636f6e73-3838-4949'
          - 'FDA50693A4E24FB1AFCFC6EB07647825-10-7'
          - 'ba0f8dd2ab16401f9664ef12390c5714-0-0'
```

**Expected behavior**
Room assistant should start without error.

**Environment**
 - room-assistant version: Latest
 - installation type: Ansible. NPM version 6.14.11, Node version 14.16.0
 - hardware: Pi 4
 - OS: Raspbian

**Additional context**
This *was* working at some point, I went to make a config change and notice this node wasn't working properly. I did re-download the playbook just for good measure and re-deployed but the issue persists. I did attempt an npm rebuild which didn't correct the issue. My pi3 and two pie zeros are still working, this is just the pi4.

**Comment by mKeRix** [comment]
This issue usually happens after a NodeJS upgrade (there was one in the playbook recently). Since the rebuild didn't work out I'd recommend to try the more brutal approach of manually uninstalling room-assistant on the problem instance `sudo npm uninstall -g room-assistant` and then re-installing it. In your case the re-installation can just be done by re-running the playbook. This will completely wipe the faulty dependency compilation and re-compile them for your current NodeJS version.

**Comment by danodemano** [comment]
@mKeRix - looks like that got it, thanks!!!!
