### ISSUE TITLE
d6t keeps wanting to install on rpi which fails

### ISSUE THREAD

**Issue by gmalbert** [mKeRix/room-assistant#75]
I'm using NodeJS 10.15.0 on a RPI Zero W. I went through the whole setup, and when I do sudo npm start, it keeps trying to install d6t and it fails every time. I know that d6t isn't supported on the RPI, but I can't get past this prompt. What should I be deleting in config files or otherwise so that I don't have this issue?

**Comment by mKeRix** [comment]
Actually the D6T library should technically compile fine even on a Raspberry, just not give any usable data. Can you send me the logs of the failing installation?

Generally the dependencies are installed based on what services you activated, so make sure that `d6t` is not in the `services` array of the config or the `SERVICES` environment variable.

Just fyi: the installation failures may also be related to the Bluetooth library, since there is an issue with it on Node 10 and the creator is not accepting the fix merge request. I will switch to a different library version this weekend so that it works on Node 10 as well. Will update you in here then as well!

**Comment by mKeRix** [comment]
Update regarding the node 10 stuff: this is fixed on master now!

**Comment by Pethson** [comment]
I get the same problem running nodeJS 11.6.0

pi@oscar_pi:~/room-assistant $ npm start

> room-assistant@1.1.1 start /home/pi/room-assistant
> bin/room-assistant-runner.js

Packages needed: mqtt@2.18.8,@abandonware/noble@1.9.2-1,onoff@3.2.2,d6t@0.0.5,moleculer-prometheus@0.2.0
Already installed: @abandonware/noble@1.9.2-1,moleculer-prometheus@0.2.0,mqtt@2.18.8,onoff@3.2.2
Now installing: d6t@0.0.5
npm WARN checkPermissions Missing write access to /home/pi/room-assistant/node_modules/d6t/node_modules/ms
npm WARN checkPermissions Missing write access to /home/pi/room-assistant/node_modules/d6t/node_modules/debug
npm WARN checkPermissions Missing write access to /home/pi/room-assistant/node_modules/d6t/node_modules/ref-struct
npm WARN checkPermissions Missing write access to /home/pi/room-assistant/node_modules/d6t/node_modules/ffi
npm WARN checkPermissions Missing write access to /home/pi/room-assistant/node_modules/d6t
npm WARN checkPermissions Missing write access to /home/pi/room-assistant/node_modules/d6t/node_modules
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/room-assistant/node_modules/ffi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/room-assistant/node_modules/ref-struct/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/room-assistant/node_modules/ffi/node_modules/debug/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/room-assistant/node_modules/ffi/node_modules/ms/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/room-assistant/node_modules/ref-struct/node_modules/debug/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/room-assistant/node_modules/ref-struct/node_modules/ms/package.json'
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.

{ [Error: EACCES: permission denied, access '/home/pi/room-assistant/node_modules/d6t/node_modules/ms']
  errno: -13,
  code: 'EACCES',
  syscall: 'access',
  path: '/home/pi/room-assistant/node_modules/d6t/node_modules/ms' }
pi@oscar_pi:~/room-assistant $ node -v
v11.6.0
pi@oscar_pi:~/room-assistant $


Regards Peter!

**Comment by gmalbert** [comment]
I commented on a similar issue that may or may not be related. Logs are there. Happy to paste again here or whatever helps in the process.
https://github.com/mKeRix/room-assistant/issues/7

**Comment by gmalbert** [comment]
Also, I removed the d6t from custom-environment-variables.json and config/local.json, but it still wants to install. Did I miss a spot to remove it?

**Comment by mKeRix** [comment]
Oddly the logs you posted do not even try to install the d6t module, but rather the bluetooth dependencies. In your case maybe try deleting the whole room-assistant directory, then clone it again, make a copy of the config file, enable `ble` and `console` in the services array and then just start it without sudo. So basically, from the directory above the room-assistant one:

```bash
rm -Rf room-assistant/
sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev libusb-1.0-0-dev
sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
git clone https://github.com/mKeRix/room-assistant.git
cd room-assistant
npm install --production
cp config/default.json config/local.json
nano config/local.json
```

Then edit the `services` field to look like `"services": ["console", "ble"],`, save and run `npm start`. This should give you a clean, working copy.

**Comment by gmalbert** [comment]
Thank you for the continued help. I followed your instructions exactly and am still getting errors. Should I reinstall my rpi image and start from scratch? From the log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/nodejs/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle room-assistant@1.1.1~prestart: room-assistant@1.1.1
6 info lifecycle room-assistant@1.1.1~start: room-assistant@1.1.1
7 verbose lifecycle room-assistant@1.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle room-assistant@1.1.1~start: PATH: /opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/n$
9 verbose lifecycle room-assistant@1.1.1~start: CWD: /home/pi/room-assistant
10 silly lifecycle room-assistant@1.1.1~start: Args: [ '-c', 'bin/room-assistant-runner.js' ]
11 silly lifecycle room-assistant@1.1.1~start: Returned: code: 1  signal: null
12 info lifecycle room-assistant@1.1.1~start: Failed to exec start script
13 verbose stack Error: room-assistant@1.1.1 start: `bin/room-assistant-runner.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/index$
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/lib/s$
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid room-assistant@1.1.1
15 verbose cwd /home/pi/room-assistant
16 verbose Linux 4.14.79+
17 verbose argv "/opt/nodejs/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error room-assistant@1.1.1 start: `bin/room-assistant-runner.js`

22 error Exit status 1
23 error Failed at the room-assistant@1.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gmalbert** [comment]
I re-imaged the pi zero w and ran through your directions. at the npm install --production stage, I'm now getting this. I haven't made any other modifications to the system.

```
(node:8939) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT: no such file or directory, open '/root/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 4.14.79+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! cwd /root
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! path /root/package.json
npm ERR! syscall open
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
```

node -v returns 8.11.1.

**Comment by gmalbert** [comment]
OK, I re-imaged my rpi zero w and followed your instructions. Had to upgrade node-js with another command and it's showing version: 10.15.0. When I run npm start (with and without sudo), I now get this. Different issue?

```
Installing dependencies for: console,ble
Packages needed: @abandonware/noble@1.9.2-1
Already installed: @abandonware/noble@1.9.2-1
Now installing:
[2019-01-26T02:28:33.095Z] INFO  basementrpi-9227/BROKER: Moleculer v0.13.4 is starting...
[2019-01-26T02:28:33.155Z] INFO  basementrpi-9227/BROKER: Node ID: basementrpi-9227
[2019-01-26T02:28:33.163Z] INFO  basementrpi-9227/BROKER: Namespace: <not defined>
[2019-01-26T02:28:33.175Z] INFO  basementrpi-9227/REGISTRY: Strategy: RoundRobinStrategy
[2019-01-26T02:28:33.209Z] INFO  basementrpi-9227/BROKER: Serializer: JSONSerializer
[2019-01-26T02:28:33.229Z] INFO  basementrpi-9227/BROKER: Registered 10 internal middleware(s).
[2019-01-26T02:28:33.935Z] ERROR basementrpi-9227/BROKER: Failed to load service '/home/pi/room-assistant/services/b                                          le.service.js' { Error: Cannot find module '@abandonware/bluetooth-hci-socket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32) code: 'MODULE_NOT_FOUND' }
Cannot read property 'prototype' of undefined TypeError: Cannot read property 'prototype' of undefined
    at ServiceBroker.getConstructorName (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:1278:2                                          0)
    at ServiceBroker.normalizeSchemaConstructor (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.j                                          s:1303:21)
    at ServiceBroker.loadService (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:540:17)
    at _.uniq.forEach.f (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:352:44)
    at Array.forEach (<anonymous>)
    at loadServices (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:352:24)
    at startBroker (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:422:2)
    at tryCatcher (/home/pi/room-assistant/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:512:31                                          )
    at Promise._settlePromise (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/room-assistant/node_modules/bluebird/js/release/async                                          .js:17:14)
```

**Comment by mKeRix** [comment]
This error points to the Bluetooth library not being installed correctly, try running the commands below and post the logs in here again.

```
npm install @abandonware/noble@1.9.2-1 --no-save --no-package-lock
npm install @abandonware/bluetooth-hci-socket --no-save --no-package-lock
```

**Comment by gmalbert** [comment]
> npm install @abandonware/noble@1.9.2-1 --no-save --no-package-lock

For the above command, I get this:

```
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ @abandonware/noble@1.9.2-1
removed 66 packages and updated 1 package in 46.745s
```

For this command: npm install @abandonware/bluetooth-hci-socket --no-save --no-package-lock, I get this:

```
> @abandonware/bluetooth-hci-socket@0.5.3-1 preinstall /home/pi/room-assistant/n                                                                   ode_modules/@abandonware/bluetooth-hci-socket
> npm install node-pre-gyp

npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-pre-gyp@0.12.0
added 66 packages in 36.155s

> @abandonware/bluetooth-hci-socket@0.5.3-1 install /home/pi/room-assistant/node                                                                   _modules/@abandonware/bluetooth-hci-socket
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/sandeepmistry/node-                                                                   bluetooth-hci-socket/releases/download/0.5.3-1/binding-0.5.3-1-node-v59-linux-ar                                                                   m.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @abandonware/bluetooth-hci-so                                                                   cket@0.5.3-1 and node@9.11.1 (node-v59 ABI, glibc) (falling back to source compi                                                                   le with node-gyp)
make: Entering directory '/home/pi/room-assistant/node_modules/@abandonware/blue                                                                   tooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::poll                                                                   ()’:
../src/BluetoothHciSocket.cpp:252:95: warning: ‘v8::Local<v8::Value> Nan::MakeCa                                                                   llback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*                                                                    ’ is deprecated [-Wdeprecated-declarations]
 back(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                              ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../../nan/nan.h:980:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::emit                                                                   ErrnoError()’:
../src/BluetoothHciSocket.cpp:283:93: warning: ‘v8::Local<v8::Value> Nan::MakeCa                                                                   llback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*                                                                    ’ is deprecated [-Wdeprecated-declarations]
 back(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                              ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../../nan/nan.h:980:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
  COPY /home/pi/room-assistant/node_modules/@abandonware/bluetooth-hci-socket/li                                                                   b/binding/binding.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/pi/room-assistant/node_modules/@abandonware/bluet                                                                   ooth-hci-socket/build'
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is i                                                                   nstalled. You must install peer dependencies yourself.

+ @abandonware/bluetooth-hci-socket@0.5.3-1
removed 3 packages and updated 1 package in 120.38s
```

Now when doing npm start, it hangs (and did so overnight) at this point:


```
> room-assistant@1.1.1 start /home/pi/room-assistant
> bin/room-assistant-runner.js

Installing dependencies for: console,ble
Packages needed: @abandonware/noble@1.9.2-1
Already installed:
Now installing: @abandonware/noble@1.9.2-1
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ @abandonware/noble@1.9.2-1
added 3 packages and removed 1 package in 26.354s
[2019-01-27T18:20:39.707Z] INFO  basementrpi-709/BROKER: Moleculer v0.13.4 is starting...
[2019-01-27T18:20:39.771Z] INFO  basementrpi-709/BROKER: Node ID: basementrpi-709
[2019-01-27T18:20:39.778Z] INFO  basementrpi-709/BROKER: Namespace: <not defined>
[2019-01-27T18:20:39.789Z] INFO  basementrpi-709/REGISTRY: Strategy: RoundRobinStrategy
[2019-01-27T18:20:39.841Z] INFO  basementrpi-709/BROKER: Serializer: JSONSerializer
[2019-01-27T18:20:39.867Z] INFO  basementrpi-709/BROKER: Registered 10 internal middleware(s).
[2019-01-27T18:20:42.228Z] INFO  basementrpi-709/REGISTRY: '$node' service is registered.
[2019-01-27T18:20:42.270Z] INFO  basementrpi-709/REGISTRY: 'console' service is registered.
[2019-01-27T18:20:42.289Z] INFO  basementrpi-709/REGISTRY: 'ble' service is registered.
[2019-01-27T18:20:42.300Z] INFO  basementrpi-709/BROKER: ServiceBroker with 3 service(s) is started successfully.
noble warning: adapter state unauthorized, please run as root or with sudo
               or see README for information on running without root/sudo:
               https://github.com/sandeepmistry/noble#running-on-linux
[            ......] - postinstall: sill install printInstalled
```

Do you want me to start over? Should I be using your commands immediately above before or after the npm install --production command?

**Comment by mKeRix** [comment]
You actually got it working now! You just need to give node permissions to access your bluetooth adapter, run:

```
sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
```

Then start room-assistant as you would normally (not as root!). :)

**Comment by gmalbert** [comment]
@mKeRix my god, it's working! Now I just need to pick out the devices and go from there. Super grateful for all of the assistance!
