### ISSUE TITLE
Fresh install rpi 3b+ failing abandonware module

### ISSUE THREAD

**Issue by Alfiegerner** [mKeRix/room-assistant#87]
Hi,

I have a new Pi 3b+, fresh install stretch raspbian and am following the install instructions here: https://github.com/mKeRix/room-assistant.

I'm using the latest npm version installed via https://github.com/nodesource/distributions/blob/master/README.md#debinstall  which is v12

On npm start I get the following:

`
pi@raspberrypi:~/room-assistant $ npm start

> room-assistant@1.1.1 start /home/pi/room-assistant
> bin/room-assistant-runner.js

Installing dependencies for: mqtt,ble,console
Packages needed: mqtt@2.18.8,@abandonware/noble@1.9.2-1
Already installed: @abandonware/noble@1.9.2-1,mqtt@2.18.8
Now installing:
[2019-06-14T21:35:44.036Z] INFO  raspberrypi-16443/BROKER: Moleculer v0.13.4 is starting...
[2019-06-14T21:35:44.046Z] INFO  raspberrypi-16443/BROKER: Node ID: raspberrypi-16443
[2019-06-14T21:35:44.048Z] INFO  raspberrypi-16443/BROKER: Namespace: <not defined>
[2019-06-14T21:35:44.050Z] INFO  raspberrypi-16443/REGISTRY: Strategy: RoundRobinStrategy
[2019-06-14T21:35:44.056Z] INFO  raspberrypi-16443/BROKER: Serializer: JSONSerializer
[2019-06-14T21:35:44.059Z] INFO  raspberrypi-16443/BROKER: Registered 10 internal middleware(s).
[2019-06-14T21:35:44.606Z] ERROR raspberrypi-16443/BROKER: Failed to load service '/home/pi/room-assistant/services/ble.service.js' Error: Cannot find module '@abandonware/bluetooth-hci-socket'
Require stack:
- /home/pi/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js
- /home/pi/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/bindings.js
- /home/pi/room-assistant/node_modules/@abandonware/noble/lib/resolve-bindings.js
- /home/pi/room-assistant/node_modules/@abandonware/noble/index.js
- /home/pi/room-assistant/services/ble.service.js
- /home/pi/room-assistant/node_modules/moleculer/src/service-broker.js
- /home/pi/room-assistant/node_modules/moleculer/index.js
- /home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js', '/home/pi/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/bindings.js', '/home/pi/room-assistant/node_modules/@abandonware/noble/lib/resolve-bindings.js', '/home/pi/room-assistant/node_modules/@abandonware/noble/index.js', '/home/pi/room-assistant/services/ble.service.js', '/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js', '/home/pi/room-assistant/node_modules/moleculer/index.js', '/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js' ]
}
Cannot read property 'prototype' of undefined TypeError: Cannot read property 'prototype' of undefined
    at ServiceBroker.getConstructorName (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:1278:20)
    at ServiceBroker.normalizeSchemaConstructor (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:1303:21)
    at ServiceBroker.loadService (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:540:17)
    at /home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:352:44
    at Array.forEach (<anonymous>)
    at loadServices (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:352:24)
    at startBroker (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:422:2)
    at tryCatcher (/home/pi/room-assistant/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:17:14)
`

I have installed this fine on several pi zeros, I'm guessing an issue with the node / npm version but thought I'd check before trying hacking at it.

(Working awesome on 5 pi zeros currently dotted around the house btw, thanks for great implementation)

**Comment by Alfiegerner** [comment]
Couldn't help but tinker .... works fine with nodejs version 10.

**Comment by mKeRix** [comment]
Glad you figured this out - sorry I didn't actually reply in a decent timeframe. Since Node considers v10 as their LTS release which is recommended for most users still I will stick to supporting that version for now. But I actually just did some dependency updates and the latest version on master compiled fine with Node 12 on my MacBook. Just for anyone stumbling across this in the future :)
