### ISSUE TITLE
Error starting the add-on (Hass.io based installation)

### ISSUE THREAD

**Issue by bardx** [mKeRix/room-assistant#97]
Hi,

I tried to install room-assistant by simply downloading it from the Hass.io add-on store (after adding the correct repository). When I try to start the add-on, it says some packages are required:

```
> room-assistant@1.1.1 start /room-assistant
> bin/room-assistant-runner.js

Packages needed: mqtt@2.18.8,@abandonware/noble@1.9.2-1,onoff@3.2.2,d6t@0.0.5,moleculer-prometheus@0.2.0
```

After a while, the installation of d6t fails with this error:

```
compilation terminated.
make: Leaving directory '/room-assistant/node_modules/d6t/library/src'
make: *** [Makefile:23: i2c-reg.o] Error 1
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.2 (node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.2 install: `prebuild-install --verbose || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

{ Error: d6t@0.0.5 postinstall: `make -C library/src/ && sudo make -C library/src install`
Exit status 2
    at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  cause: 
   { Error: d6t@0.0.5 postinstall: `make -C library/src/ && sudo make -C library/src install`
Exit status 2
    at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
     errno: 2,
     code: 'ELIFECYCLE',
     pkgid: 'd6t@0.0.5',
     stage: 'postinstall',
     script: 'make -C library/src/ && sudo make -C library/src install',
     pkgname: 'd6t' },
  errno: 2,
  code: 'ELIFECYCLE',
  pkgid: 'd6t@0.0.5',
  stage: 'postinstall',
  script: 'make -C library/src/ && sudo make -C library/src install',
  pkgname: 'd6t',
  parent: 'room-assistant' }
```

Anyone knows what's the problem?
Thanks!

**Comment by chopperpl** [comment]
I have the same issue. Hassio 104.1 on RP3b+

**Comment by mKeRix** [comment]
Could you share with me which components you have enabled? I see that it is trying to install pretty much every optional dependency and failing on the d6t one - which isn't supported on Hass.io yet (see docs). Do you intend to use the d6t component?

**Comment by mKeRix** [comment]
Should also not be an issue anymore with 2.0!
